### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by cmboling** [newrelic/newrelic-ruby-agent#1037]
### Is your feature request related to a problem? Please describe.

I noticed in the README there's a section describing the license, which is Apache 2.0. Please add a license file, so developers can do a quick lookup on a license file rather than the readme. 😸 

### Priority

Must Have

**Comment by cmboling** [comment]
Nvm!!!

**Comment by fallwith** [comment]
Hi @cmboling, thanks very much for looking through the README and raising this issue.

Even though you ended up finding our `LICENSE` file in the root of the repo and closing this issue, your suggestion was still helpful because it prompted us to look at our other `newrelic` namespaced repos and find some minor inconsistencies between our license related documentation that we're going to discuss. This is much appreciated, thank you!
