### ISSUE TITLE
Mark multiple loggers from the same source for skip instrumenting

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1039]
Goal: Prevent log events with duplicate severities, messages, and timestamps for the same entity from being sent up to New Relic twice

Working solution:
Maintain a hash with Logger instance object ids as keys and log device references as values to answer these questions:

- Are you one of multiple loggers? (does more than 1 key exist in the hash?)
- Is your log device set to write to STDOUT/STDERR?

If the logger answers yes to both, then it is marked for skipping. If it has already been marked for skipping, the logger will not get asked the questions again.

**Comment by fallwith** [comment]
At this point, we consider the objective here to ultimately represent a premature optimization. When implemented exactly as described, we run the risk of not reporting on legitimate log data just because it is destined for a standard stream. We will err on the side of reporting too much and then revisit later if duplication or other unwanted recordings are reported that can be addressed with this type of work.
