### ISSUE TITLE
Span Parent ID not set properly using Async Transaction workaround

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1056]
We have a functional workaround for allowing threads to be traced as unique operations within a transaction, however, the parents are not correctly assigned in all cases and sometimes concurrent threads appear as children of each other. This occurs in both the Transaction and Distributed Tracing views. 

Also, in other cases there is a warning raised with this approach that states the parent ID for the span is not being set properly.

This ticket is to investigate the cause and create a solution.

**Comment by tannalynn** [comment]
It looks like we will need to add some instrumentation to `Thread` in order to make this work. Since that is the case, I suspect it will actually be pretty straightforward to allow the agent to automatically bring `Thread.current[:newrelic_tracer_state]` into the new thread (would be a step further than documenting it as in https://github.com/newrelic/newrelic-ruby-agent/issues/1057, it would allow the agent to do it on it's own).
