### ISSUE TITLE
Investigate: Improve Rails trace naming

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#1424]
### Description
Sometimes traces/transaction names for Rails apps have names that come from the Rails framework code rather than from the customer's apps. These traces provide little value for customers because they cannot take action on them/connect them to their codebase. 

Some examples of transaction names are: 
* Controller/Middleware/Rack/ActionDispatch::Routing::RouteSet/call
* Middleware/Rack/ActionDispatch::Executor/call 

There may be others. Looking at Rails apps within our company or large customer apps may help determine other trace names to eliminate.

This is also not always consistent. Sometimes a controller action is used for the transaction name most of the time, but additional refreshes will display one of the above names instead.

We might want to look at `NewRelic::Agent::Transaction#best_name` as a potential culprit. The Transaction class has many other methods related to naming that could also be looked at.

### Acceptance Criteria
* Customer transactions include only names that can be directly located within their codebase

### Design Consideration/Limitations
* This needs to be completed as part of a major version release because it will change the grouping of data, causing metrics/information to hold different information than prior to this change

### Dependencies
None I can think of

### Additional context
Some discovery to identify additional framework traces should be considered a prerequisite to this task. It can be completed with this story or another.

### Estimates
M

**Comment by kaylareopelle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Ruby-Agent-578cc3351c7940044e18b71e/issues/newrelic/newrelic-ruby-agent/1424?planning-poker) with Zenhub @fallwith @hannahramadan @tannalynn

**Comment by tannalynn** [comment]
After investigating this issue, we were able to determine that transactions with this name can be caused by a variety of situations. These transactions represent a route (or other rails middleware) in a rails app that calls code that is not instrumented by new relic. Since the rails middleware IS instrumented, we still see the transaction, but additional details about the transaction are unavailable due to a lack of instrumentation. This could happen because a controller does not inherit from ActionController::Base, or the route is sent directly to a gem that does not have new relic instrumentation. 

These transactions are still important for the customer to see because the rails middleware instrumentation can still capture performance issues/long running transactions, but there is no additional information available to the ruby agent to better name these transactions.

After some internal discussions and additional research, we determined that since the agent is unable to determine a better name due to lack of instrumentation, but the transactions can still be important to customers, the best way to address this issue is to add a [troubleshooting guide](https://github.com/newrelic/docs-website/pull/15178) to the docs site that will explain the cause of these generically named transactions and potential solutions.
