### ISSUE TITLE
Investigate: Observe Sidekiq 7 metrics

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1479]
Sidekiq 7 (currently in beta) will have built-in support for metrics reporting, viewable via Sidekiq's own web UI.

It's possible that New Relic customers would like to have these metrics collected by the Ruby agent to some degree. We should investigate.

https://github.com/mperham/sidekiq/wiki/Metrics

**Comment by fallwith** [comment]
https://www.mikeperham.com/2022/10/27/introducing-sidekiq-7.0/

**Comment by tannalynn** [comment]
Sidekiq metrics display time info related to the jobs and number of success/failures for each job. 

Since we already are recording time related information, there isn't anything new for us to gain with those metrics.

For the success and failures, we aren't directly recording number of failures or successes for jobs. However, jobs seem to only be considered failures when an error occurs, which _is_ something the agent keeps track of. 
If we wanted to add specific success/failure data, we could create some metrics for each job to record the number of failures and successes. The way the sidekiq metrics gets the success/fail info looks to be by querying the job results when loading up the metrics page, so it doesn't seem like there is anything new for us to hook into specific to success or failure, but we could record after the job is done each time and increment the appropriate metric.

**Comment by kaylareopelle** [comment]
@tannalynn  - Thanks for taking a closer look!

**Users!** If you use New Relic and are interested in the specific success/failure metrics available in Sidekiq 7, please give us some sort of feedback on this issue (emoji response, comment, etc.)

**Comment by fallwith** [comment]
Internal FR link: https://issues.newrelic.com/browse/NR-138200

**Comment by kford-newrelic** [comment]
Blocked; may not be appropriate for the Ruby Agent to implement

**Comment by elucus** [comment]
This is better suited to using an OHI and has been transferred to another team. Review the internal ticket for details.
