### ISSUE TITLE
Investigate: CI failure with Sidekiq 7

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1567]
**Note: As a core technology, we have 90 days to adopt this change. This is due January 25, 2023**

Sidekiq 7 was released on October 27 and is currently causing the CI to fail. Here is the [Github action run](https://github.com/newrelic/newrelic-ruby-agent/actions/runs/3340197998/jobs/5530323161) for more information. The same failure appeared a few times:
```
  1) Error:
SidekiqTest#test_agent_posts_correct_metric_data:
NoMethodError: undefined method `logger=' for Sidekiq:Module

    Sidekiq.logger = string_logger
           ^^^^^^^^^
Did you mean?  logger
```

We've stopped testing the latest version of Sidekiq by commenting out the pinned `[nil,2.5]` from `test/multiverse/suites/sidekiq/Envfile` (lines 10 and 11). Once the failure is addressed, we can resume testing the latest version of Sidekiq.

**Comment by fallwith** [comment]
`Sidekiq.logger=` seems to have moved to `Sidekiq::Config#logger=`, so that's an easy enough change to accommodate.

Unfortunately, there seem to be other issues lying in wait once we resolve the `logger=` one. We now see 9 timeout errors...


```shell
  1) Error:
SidekiqTest#test_arguments_are_captured_on_transaction_and_span_events_when_enabled:
Timeout::Error: execution expired
    <internal:thread_sync>:18:in `pop'
    ~/git/public/newrelic-ruby-agent/test/multiverse/suites/sidekiq/test_worker.rb:57:in `block (2 levels) in wait'
```

**Comment by fallwith** [comment]
In progress PR: https://github.com/newrelic/newrelic-ruby-agent/pull/1607

**Comment by fallwith** [comment]
Example of the new timeout failure now that the `logger=` issue has been resolved:

https://github.com/newrelic/newrelic-ruby-agent/actions/runs/3425092395/jobs/5705523947#step:11:428

**Comment by fallwith** [comment]
In `sidekiq/test_worker.rb`, there's a `TestWorker` class with a `self.wait` method defined. This method accesses the `@done` object - of class `Thread::Queue` - and attempts to call `#pop` on it until it is empty. Unfortunately, it starts out empty when `self.wait` is called, and the `#pop` call simply hangs indefinitely.

**Comment by kaylareopelle** [comment]
It looks like our instrumentation isn't getting hit by the tests at all. A `binding.irb` in our instrumentation's Server and Client `call` methods was never hit! I'm going to look into what might have changed structurally with Sidekiq's instrumentation API.

**Comment by fallwith** [comment]
Agent versions v8.12.0 and below are now thought to be incompatible with Sidekiq v7.0, owing to an attempt to instrument delayed extensions, which have been dropped from v7.0.

Here is the PR to have agent v8.13.0 support Sidekiq v7.0:
https://github.com/newrelic/newrelic-ruby-agent/pull/1615

**Comment by fallwith** [comment]
Investigation findings:

* The issue with the Sidekiq `logger=` method having been moved only impacted our unit tests and not the agent's instrumentation code. The tests have been updated with PR #1615 
* The root cause of the agent logging an error about failed Sidekiq instrumentation installation was determined to be the agent's attempt to still instrument Delayed Extensions which were removed from Sidekiq starting with v7.0. The agent will no longer attempt to instrument Delayed Extensions when Sidekiq is at or above v7.0.0 via the updates in PR #1615.
* The new Sidekiq client and server middleware base classes are now being inherited from. The agent's own middleware is not directly performing Sidekiq `redis` and `logger` calls, so we're not actually using the new middleware base class content yet, but it is in place for futureproofing as of PR #1615.
