### ISSUE TITLE
Elasticsearch ruby generating a StackLevelTooDeep

### ISSUE THREAD

**Issue by rexmadden** [newrelic/newrelic-ruby-agent#1590]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
After upgrading to 8.12.0, Elasticsearch ruby was generating a StackLevelTooDeep whenever a search to localhost 
was attempted

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
It looked like it was trying to call cluster/health over and over again. Disabling Elasticsearch instrumentation solved the problem

```
  instrumentation:
    elasticsearch: disabled
```

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by tannalynn** [comment]
Hello @rexmadden 
Thanks for letting us know about this issue. The most common cause of stack level too deep errors related to the ruby agent is usually caused by a [Module#prepend and method chaining conflict](https://docs.newrelic.com/docs/apm/agents/ruby-agent/troubleshooting/systemstackerror-stack-level-too-deep/) with another gem. The ruby agent uses Module#prepend by default for our instrumentation, but sometimes another gem will be using method chaining on the same method we are interacting with, which can lead to a stack level too deep error. 

Have you tried setting the elasticsearch instrumentation to use method chaining instead of Module#prepend? Adding the following in your newrelic.yml may resolve the issue. 
```
  # newrelic.yml

  instrumentation:
    elasticsearch: chain
```

If this doesn't resolve the issue, let me know! Also, if this doesn't resolve the issue, it would be helpful to [get the non truncated stack trace](https://docs.newrelic.com/docs/apm/agents/ruby-agent/troubleshooting/systemstackerror-stack-level-too-deep/#1-get-the-full-stack-trace) showing the repeating lines of code to give me a better idea of what it's getting stuck on. 
Hopefully this helps!

**Comment by kaylareopelle** [comment]
Hi @rexmadden ! Let us know if you're still having problems with Elasticsearch instrumentation. Since we haven't heard back from you in a while, we're going to close this issue.
