### ISSUE TITLE
Document how to add custom attributes at the end of Rails controller

### ISSUE THREAD

**Issue by fuxinhao-crypto** [newrelic/newrelic-ruby-agent#1684]
### Is your feature request related to a problem? Please describe.
I'm trying to add some custom attributes by calling `::NewRelic::Agent.add_custom_attributes`. I've used Railtie to add custom attributes on controller start and it works great. But when I tried to use Rack middleware to add custom attributes after a controller action has run. It doesn't work. 

My Rack middleware: 
```
module NewRelic
  module Rack
    class CustomAttributeMiddleware
      def initialize(app)
        @app = app
      end

      def call(env)
        res = @app.call(env)

        ::NewRelic::Agent.add_custom_attributes({my_key: "my_value"})

        res
      end
    end
  end
end

# config/environments/production.rb
Rails.application.configure do
  ...
  config.middleware.use NewRelic::Rack::CustomAttributeMiddleware
end
```

I don't even know if it's an appropriate way to do that using Rack middleware. I think this is a common usage. Could u advise here? 

### Feature Description
Document how to call `::NewRelic::Agent.add_custom_attributes` at the end of Rails Controller

### Additional context
rails (5.2.8.1)
newrelic_rpm (8.10.0)

### Priority
Nice to have

**Comment by fallwith** [comment]
Hello @fuxinhao-crypto,

Thank you for your interest in using custom attributes and for describing things so well.

I believe you have 2 options to accomplish what you would like to do:

### Option 1 - Continue to use Rack Middleware

Your middleware code (hopefully located somewhere such as `lib/middleware/new_relic.rb`) and your `config/environments/production.rb` code both look great!

My hypothesis is you are not seeing your custom attributes because the New Relic Ruby agent does not understand that you want the attributes to be a part of the controller action's transaction data being reported to New Relic. In order to give the agent some help, you can [add a transaction tracer](https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation/#transaction-tracers).

Using your existing middleware code, you would make the following additions:

```diff
+ require 'newrelic_rpm'
+
module NewRelic
  module Rack
    class CustomAttributeMiddleware
+     include ::NewRelic::Agent::Instrumentation::ControllerInstrumentation
+
      def initialize(app)
        @app = app
      end

      def call(env)
        res = @app.call(env)

        ::NewRelic::Agent.add_custom_attributes({my_key: "my_value"})

        res
      end
+     add_transaction_tracer :call
    end
  end
end
```

By telling the agent that your middleware's `call` method is important, it should be able to correctly report your custom attributes as desired.


### Option 2 - use around_action inside your controller class

You mentioned that you want to report custom attributes "after a controller action has run". In a Rails controller, you can use `around_action` to specify code to be ran "around" (before and after) the controller methods calls. You would simply define a custom method, have your "before" code happen before the `yield`, have your "after" code happen after the `yield` and then reference the custom method via `around_action`. Here is an example:

```ruby
class ExampleController < ApplicationController
  around_action :report_custom_attributes

  def index
    render text: 'Hello'
  end

  private

  def report_custom_attributes
    yield
    ::NewRelic::Agent.add_custom_attributes({my_key: "my_value"})
  end
end
```

I have just tested both of these options with Rails 5.2.8.1 and newrelic_rpm 8.13.1 and they work for me. Please let us know if they work for you. If they do, we will work on updating our documentation.

Thank you again for contacting us!

**Comment by fallwith** [comment]
That's great news, @fuxinhao-crypto! I'm very glad. I will talk with our dev and docs teams about updating our custom attributes documentation.
