### ISSUE TITLE
CI: need to conditionally reference ActiveRecord instead of ActiveRecord::Base for timestamped migrations

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#1751]
As per this CI warning appearing in our Rails Edge CI tests:

```
DEPRECATION WARNING: ActiveRecord::Base.timestamped_migrations is deprecated and will be removed in Rails 7.1.
Use `ActiveRecord.timestamped_migrations` instead.
 (called from block in test_active_record_initializer_config_change_not_saved_when_agent_initialized_before_config_initializers at ~/git/public/newrelic-ruby-agent/test/new_relic/newrelic_rpm_test.rb:80)
```

We should update our tests that use `timestamped_migrations` to automatically detect support for `ActiveRecord.timestamped_migrations` and use it when present. When not present, we'll need to fall back to `ActiveRecord::Base.timestamped_migrations` for the older Rails versions.

**Comment by kaylareopelle** [comment]
@fallwith - I think we're already doing this. Looking in our codebase, this is the only reference to `ActiveRecord::Base.timestamped_migrations` and we have a clause set for Rails 7.1. Since we support older versions of Rails, including the one with the deprecation warning, it won't go away.

https://github.com/newrelic/newrelic-ruby-agent/blob/1e989f10338b802626635b83502fe319c18f0347/test/new_relic/newrelic_rpm_test.rb#L77-L82

**Comment by kaylareopelle** [comment]
The code surrounding this problem has been removed from the codebase.
