### ISSUE TITLE
Uncaught (in promise) ChunkLoadError: Loading chunk 692 failed.

### ISSUE THREAD

**Issue by guillaumebriday-pa** [newrelic/newrelic-ruby-agent#1820]
## Description
For some reasons, a chunk starts to fail loading:

<img width="756" alt="Screenshot 2023-02-10 at 15 47 17" src="https://user-images.githubusercontent.com/89008587/218194623-741cd0f2-9ec6-4d2c-9e97-162fa84fbdb3.png">

I didn't change anything and it starts failing. Any idea why and how to fix it?

## Your Environment
Newrelic version: `newrelic_rpm (8.16.0)`
Ruby version: 3.0.4
Rails version : 6.1.7.2

**Comment by tblais1224** [comment]
Experiencing the same issue, any updates on this?

**Comment by pilgunboris** [comment]
We faced the same issue. It broke JS on a few pages of the app. 
I hope the workaround will be found soon.

**Comment by cwli24** [comment]
Will be properly silenced into a warning in upcoming v1225 cut!

**Comment by tannalynn** [comment]
@guillaumebriday-pa Thanks for letting us know about this issue! This appears to be related to the browser agent, and will be fixed in browser agent version [1225](https://github.com/newrelic/newrelic-browser-agent/blob/main/CHANGELOG.md#fix-uncaught-promise-error-introduced-in-v1223) (thanks @cwli24!)
I'll be closing this issue as it is not a ruby agent issue. Please see https://github.com/newrelic/newrelic-browser-agent/issues/392 for more information.
