### ISSUE TITLE
SyntaxError: Unexpected token '.' thrown from included JavaScript

### ISSUE THREAD

**Issue by ekieffer-3** [newrelic/newrelic-ruby-agent#1830]
## Description
JavaScript loaded with `newrelic_rpm` `gem` throws `SyntaxError: Unexpected token '.'`

## Expected Behavior
No JavaScript error thrown.

## Steps to Reproduce

1. Create a Rails app with `gem "newrelic_rpm"` in `Gemfile`
2. [Configure](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/) the agent as needed.
3. Visit page with one of the browser versions mentioned below.
4. Observe error thrown in console ("Web Inspector" for Safari, "DevTools" for Chrome)

## Your Environment
- Ruby v2.7.6
- Rails v6.1.7.2
- `gem "newrelic_rpm"` v8.16.0
- Safari  <= v13.0.5 or Chrome <= v93.0.4577.78

## Additional context
As it occurs normally, buried in minified script:

<img width="453" alt="Screen Shot 2023-02-17 at 7 04 08 PM" src="https://user-images.githubusercontent.com/87320905/219823214-9147a35a-e4f5-4083-86d7-f79c9e8ea45a.png">

So, I captured the script, "unminified" it, and loaded it directly to see the specific offending line, which is shown below:

<img width="1017" alt="Screen Shot 2023-02-17 at 6 35 41 PM" src="https://user-images.githubusercontent.com/87320905/219822888-1908f23a-0b3d-4c0f-a0ad-8f5765f338cc.png">

**Comment by tannalynn** [comment]
Hello @ekieffer-3 

Thanks for letting us know about this issue. Unfortunately, this appears to be an issue related to the New Relic Browser Agent, not the ruby agent. While the ruby agent does help the browser agent get installed, we don't have much control over the javascript code the browser agent uses or the ability to make updates to the code. I recommend reporting this issue in the [Browser Agent repo](https://github.com/newrelic/newrelic-browser-agent) so you can get the right eyes on this issue to get this resolved.  

One option that is available from the ruby agent side of things is to set the following configuration option to false disable the browser agent until this issue is resolved. 
```
# newrelic.yml
browser_monitoring:
  auto_instrument: false
```

**Comment by tannalynn** [comment]
I checked in with the browser agent team to let them know about this issue, and they pointed out that this appears to be an unsupported browser version. Please see the [Browser agent compatibility requirements](https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring/) for more details about supported browser versions.

**Comment by ekieffer-3** [comment]
@tannalynn thank you for the follow-up and direction regarding the proper repo - my mistake. On top of that, I especially appreciate that you reached out to that team in advance and provided additional support details. All the best!
