### ISSUE TITLE
Weird Web transactions time after update

### ISSUE THREAD

**Issue by tiwi** [newrelic/newrelic-ruby-agent#1913]
I recently updated agent version from 8.12.0 to 9.0.0 and noticed that APM is showing weird time on the chart Web transactions time. Response time is not a sum of Middleware, Ruby, Postgres, Redis and Web external anymore. And now Ruby exceeds the total Response time that doesn't make sense for me.

My environment: Ruby 2.7.6, Rails 7.0.4.3 running on Ubuntu 22.04

![Zrzut ekranu 2023-03-29 o 16 55 28](https://user-images.githubusercontent.com/261330/228586901-8578ed6d-5355-48d5-9b82-891de69a054d.png)

**Comment by fallwith** [comment]
Hi @tiwi,

Thank you for bringing this issue to our attention. We believe that you may be seeing a change based on our new thread instrumentation.

With version 8.7 of the agent, we introduced improved compatibility with asynchronously operating applications by instrumenting Ruby's `Thread` class. Then in version 9.0 we further improved this compatibility by instrumenting the `Fiber` class and we also enabled the thread instrumentation by default.

Prior to having thread instrumentation, the agent could only report on the primary thread for the standard MVC lifecycle of a Rails request. If the application was using threads to do multiple things at once during the request or to continue to do some cleanup work after generating a response, the agent would be blind to that additional activity.

Now with v9.0 the agent is capable of reporting information about everything the Ruby application does across every thread. As a result, the total time shown may look different because it represents the total time taken across all threads and not just the time taken to issue a response to a request. Essentially the total time is CPU time as opposed to wall clock time. Knowing the wall clock time is still important though, so we continue to report on "response time". The dark blue line in your screenshot shows this "response time" value. This time should remain consistent with your times reported by earlier agent versions.

If you wish to revert back to the old behavior and not have the agent report on what is taking place inside of threads, you can add `instrumentation.thread: disabled` to your `newrelic.yml` config file.

If you prefer to continue to explore the new data provided with thread instrumentation, the transactions list should identify all of the individual activity that was reported. If you choose to continue with the thread instrumentation, we would love your feedback on how we could improve the organization and displaying of information across our dashboard views. Any suggestions you have will be shared with our UI/UX teams. Thank you!

**Comment by tiwi** [comment]
@fallwith Thank you for the detailed clarification! I can confirm that adding both `instrumentation.thread: disabled` and `instrumentation.fiber: disabled` settings to the config file resolved my issue. For me it was completely unexpected behavior on the Web transactions chart as I couldn't see how much of the response time was spent in the ruby code. I guess the issue can be closed.
