### ISSUE TITLE
New Relic: Downloading runtime APIs failed

### ISSUE THREAD

**Issue by zohaib-sarwar-confiz** [newrelic/newrelic-ruby-agent#2020]
Web browser console is reporting a java script error related to New Relic

## Description
I have updated by rails application a couple of day back. I am getting the following error in web browser console
![Screenshot from 2023-05-19 01-53-16](https://github.com/newrelic/newrelic-ruby-agent/assets/4044881/8cd9983d-9a60-4948-a51f-04ad890e9141)

## Your Environment
Old environment: 
Ruby 2.4
Rails 3.2
Agent: 5.0.0

Current environment:
Ruby 2.7.7
Rails 5.2.8.1
Agent: 9.2.2

I am a sort block because of the issue. Please guide me to resolve the issue. Thanks

**Comment by fallwith** [comment]
Hi @zohaib-sarwar-confiz,

Congratulations on what sounds like a very big upgrade process, and I am sorry to hear that you are encountering some issues that weren't present before.

By default in both v5.0.0 and v9.2.2 of the New Relic Ruby agent, a `<script>` JavaScript HTML tag will be inserted into rendered HTML view content. This tag will instruct the user's browser to fetch and activate the [New Relic browser agent](https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/). By using the Ruby agent and browser agent in tandem, client-side page related metrics are reported on in addition to the server-side metrics that the Ruby agent provides. This is intended to provide a complete picture of a full stack application.

Do you know if you were successfully using the New Relic browser agent previously? If so, are you aware of any view layer and/or JavaScript changes that you have made to the application as part of the upgrade process?

In order to prevent the Ruby agent from adding the `<script>` tag to HTML content, you can add `browser_monitoring.auto_instrument: false` to your `newrelic.yml` config file.

The Ruby agent itself should continue working even if the browser agent fails to download or initialize, but disabling the browser agent with that configuration option should prevent the errors entirely.

If you were using the browser agent successfully before and/or want to get the browser agent working now...

We maintain a [list of compatibility requirements](docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring/#browser-types) for the browser agent that I am providing for you to review.

We also have [Ruby agent specific documentation for the browser agent](https://docs.newrelic.com/docs/apm/agents/ruby-agent/features/new-relic-browser-ruby-agent/). That page contains a "Troubleshooting" section that might be useful.

The browser agent is open source and maintains its own GitHub repository at [newrelic/newrelic-browser-agent](https://github.com/newrelic/newrelic-browser-agent). That repository may have information or existing known issues that could be useful.

I hope this information is helpful. Please let me know the answers to the questions above. I can try to consult with someone from our browser agent team to help if need be.

--

P.S. Because you completed such a big upgrade, I want to make sure you have had a chance to review our migration guides for the Ruby agent.

- [Upgrading from v6 to v7](https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/migration-7x-guide/)
- [Upgrading from v7 to v8](https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/migration-8x-guide/)
- [Upgrading from v8 to v9](https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/migration-9x-guide/)

The only change related to the browser agent should be that the Ruby agent stopped supporting the `browser_monitoring.capture_attributes` configuration parameter and replaced it with a new `browser_monitoring.attributes.enabled` parameter instead. But there might be some other important upgrade information in those documents that might be relevant to your application.
