### ISSUE TITLE
Deprecated API methods still in code

### ISSUE THREAD

**Issue by cagmz** [newrelic/newrelic-ruby-agent#2148]
## Description

With https://github.com/newrelic/newrelic-ruby-agent/pull/544, the changelog was update with the following:

```
* **Removed deprecated api methods**

    Previously the api methods `create_distributed_trace_payload` and `accept_distributed_trace_payload` were deprecated. These have now been removed. Instead, please see `insert_distributed_trace_headers` and `accept_distributed_trace_headers`, respectively.
```

However, the `create_distributed_trace_payload` and `accept_distributed_trace_payload` methods are still present throughout the Agent:

https://github.com/search?q=repo%3Anewrelic%2Fnewrelic-ruby-agent%20create_distributed_trace_payload&type=code

## Expected Behavior
Deprecated API methods should be removed from the code.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by hannahramadan** [comment]
Hi [@cagmz](https://github.com/cagmz)! While we removed `create_distributed_trace_payload` and `accept_distributed_trace_payload` from our [public API](https://www.rubydoc.info/github/newrelic/newrelic-ruby-agent/NewRelic/Agent), we still rely on these methods for internal agent workings, which is why they are still present in agent code.

I see why this is a bit confusing, but everything should be working as expected and I'm going to close this issue. Thanks for submitting this and please raise anything else that you come across that doesn't seem right.

**Comment by cagmz** [comment]
Thanks, Hannah! Hi from Procore! 😄

**Comment by hannahramadan** [comment]
Oh hi, from an ex-Procorian 👋
