### ISSUE TITLE
What does Ruby/Fiber instrumentation helps with?

### ISSUE THREAD

**Issue by sobrinho** [newrelic/newrelic-ruby-agent#2296]
## Description
We recently upgraded from 8.15.0 to 9.5.0 and we started to see Ruby/Fiber as the most consuming portion of transactions:

<img width="342" alt="Screen Shot 2023-10-27 at 11 21 16" src="https://github.com/newrelic/newrelic-ruby-agent/assets/26460/9d820974-c851-49f3-87e9-14389cb28330">

_The purple instrumentation is the Ruby/Fiber._

Another user reported the same a while back and the recommendation was to disable the Fiber instrumentation: https://github.com/newrelic/newrelic-ruby-agent/issues/1913.

What we want to understand is how 84s was spent on Ruby/Fiber for a transaction that itself took only 3s.

## Expected Behavior
A clear documentation of how to interpret that instrumentation.

It's not clear what it is trying to say to us and here I'm being optimistic that there's a real purpose/value for that instrumentation to be enabled by default.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
N/A

## Steps to Reproduce
N/A

## Your Environment
N/A

## Additional context
N/A

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by fallwith** [comment]
Hi @sobrinho,

Thanks very much for reaching out with this issue. I appreciate the questions you raise about the instrumentation's usefulness and your optimism about there being a reason for why this functionality was created!

The agent's Thread/Fiber instrumentation doesn't discriminate with any criteria for a newly spawned thread or fiber whose `new` call came from the same fiber as the existing transaction. As a result, for applications that only see new threads and fibers spawned during a transaction that are directly related to that transaction, the increased visibility into what is going on in the threads/fibers can be extremely helpful. Conversely, if the application spawns threads or fibers that are not particularly related to the transaction, the extra information can seem either confusing or downright useless.

For an application that uses threads for a synchronous / blocking request, it can be invaluable to a user to see what database and network calls were performed inside of threads for the duration of the synchronous call. For an application that uses threads to fire off asynchronous / non-blocking calls that do not need to complete before a response is issued, it can be confusing or frustrating to see thread activity associated with the same request.

> What we want to understand is how 84s was spent on Ruby/Fiber for a transaction that itself took only 3s.

Without drilling into the exact transaction with the New Relic web UI, I can offer a hypothesis for what happened here.

A significant event such as a Ruby on Rails controller action being called took place and the agent took notice and started a new transaction. While the action was taking 3 seconds to complete, a `Thread.new` call was performed. The thread that resulted from the `Thread.new` call ended up living for 84 seconds. Clearly, because the action itself completed in 3 seconds, the result of the new thread's operation was not required for the completion of the action. From the perspective of looking at the New Relic web UI and seeing what looks like an indication that a transaction took 84 seconds while it really only took 3 seconds from the primary thread's perspective, I can absolutely see how that is confusing.

Another thing that happens with thread instrumentation that may not be happening here in your case is that multiple new threads will result in having their individual elapsed times summed. So if 5 threads are spawned that each take only 2 seconds to complete, New Relic will report that 10 seconds were spent on `Ruby/Thread`. This is true. 10 seconds were indeed spent in CPU time despite the fact that only 2 seconds elapsed from the wall clock's perpective. The existing New Relic web UI for Ruby transactions does not always do a great job in helping distinguish between cpu time and wall clock time, which can also be confusing.

Instrumentation for Thread and Fiber was enabled by default in version 9.0.0 of the agent and with the freshly released 9.6.0 version keeping it on by default still seems to make sense for the majority of customers. We are always evaluating what makes sense with defaults, and always welcome community feedback and suggestions.

In addition to considering whether the instrumentation should be enabled by default, we are also always looking for ways to improve the functionality itself. With [#2300](https://github.com/newrelic/newrelic-ruby-agent/issues/2300) we hope to produce some documentation that better conveys the value of the Thread/Fiber instrumentation. With [#2301](https://github.com/newrelic/newrelic-ruby-agent/issues/2301) we will be looking for ways to improve what gets captured and reported within threads and fibers. And with [#2302](https://github.com/newrelic/newrelic-ruby-agent/issues/2302) we'll explore an idea of continuing to report on everything happening in a new thread, but placing the new thread's activity in a separate transaction whose start time merely intersects with the start and finish time of the original thread.

If you can think of anything else that we could do to improve your experience with the agent, do please comment on those existing issues or create new ones. I am going to go ahead and close this issue and remove its "bug" label and allow the other issues to track our progress with the instrumentation. But do feel free to post additional comments or questions here.

Again, thanks for reaching out. Our team of Ruby devs is quite passionate about providing fellow Rubyists with the best possible experience.
