### ISSUE TITLE
Roda app: After upgrading agent, memory went up

### ISSUE THREAD

**Issue by megatux** [newrelic/newrelic-ruby-agent#2317]
## Description

Upgrading gem, my Roda app in Heroku, with 2 dynos w/512mb each, the memory went up above the limit, > 700mb. `Gemfile.lock` diff:

```diff
-    newrelic_rpm (9.2.2)
+    newrelic_rpm (9.6.0)
+      base64
```
## Your Environment

ruby 3.1.3
Roda 3.74.0

### Heroku metrics screenshot showing the pre, post deploy and later rollback:
 
<img width="1189" alt="Captura de pantalla 2023-11-14 a la(s) 13 12 56" src="https://github.com/newrelic/newrelic-ruby-agent/assets/850020/1d3514db-6b61-4589-a64d-f6f96703d38b">

**Comment by tannalynn** [comment]
Thanks for letting us know about your experience with upgrading the agent. 


In 9.4.0, we introduced auto-instrumentation for Roda, which provides more insight into your transactions, but could also result in an increase in agents memory usage due to recording more data. If you do not want this additional information, you could try disabling the Roda instrumentation by setting the config `instrumentation.roda` to `disabled` in your newrelic.yml. 
We introduced instrumentation for several other gems recently as well, including stripe, httpx, ethon, and Async::HTTP. In general, you can disable instrumentation for any of our supported gems by disabling the [configuration option](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#instrumentation).


You can also configure the agent to store less data to help decrease the agents memory usage using these configuration options:
```
transaction_events.max_samples_stored
span_events.max_samples_stored
application_logging.forwarding.max_samples_stored
custom_insights_events.max_samples_stored (if you're using custom events)
```
You can find more details about all of these config options [here](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration).


Hopefully that helps explain why memory usage might increase in the ruby agent, and some ways you can decrease how much memory the agent uses in your application.

**Comment by megatux** [comment]
Thanks. I read about Roda support and some new options. So, disabling Roda instrumentation should have the _same features_ as before the upgrade?

**Comment by tannalynn** [comment]
Yes, it should work the same as before since it will skip installing the new code.

**Comment by megatux** [comment]
Thanks. I just disabled the Roda instrumentation with the env. var and seems to work fine now.
  
Just in case, I'm adding screenshots where I see lot of new object allocations in the heap and GC work. Maybe that could help in future tuning.

<img width="760" alt="Captura de pantalla 2023-11-14 a la(s) 16 15 13" src="https://github.com/newrelic/newrelic-ruby-agent/assets/850020/c905636b-9849-4d50-962e-e281b68ce82a">
 
<img width="404" alt="Captura de pantalla 2023-11-14 a la(s) 16 15 30" src="https://github.com/newrelic/newrelic-ruby-agent/assets/850020/7848b83f-1d3b-4580-9e61-d4eadaae4148">
