### ISSUE TITLE
Spec: Add support for json logs

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#2358]
Once this spec has been updated and merged, we should implement changes to align with spec on how the agent should handle json logs for the log instrumentation. This spec is still undergoing discussion and changes, so we should wait to implement any changes related to it for now. 

[Spec PR](https://source.datanerd.us/agents/agent-specs/pull/652)

**Comment by hannahramadan** [comment]
Closing this ticket because this spec isn't necessarily widely applicable to Ruby. The spec references the inclusion of a `message` attriubte for logs, but not all json logging tools actually include a message. While support for JSON will need to be addressed, let's address it at the individual instrumentation level vs a generalized pattern. As additional JSON instrumentation are added, it may be worth it to visit adding an abstracted JSON logs class/ refactor instrumentation, but that will still look different than what this spec is calling for.
