### ISSUE TITLE
Memory Leak for HTTPX Integration

### ISSUE THREAD

**Issue by yuma-brendan** [newrelic/newrelic-ruby-agent#2386]
## Description
We're seeing a memory leak since upgrading the new relic agent with HTTPX support. Here are representative sidekiq processes with and without httpx instrumentation. 

![image](https://github.com/newrelic/newrelic-ruby-agent/assets/129777267/fd491765-43ee-4d8a-bcba-cb38b129eb8c)
[0] Memory bloat with HTTPX instrumentation enabled. This will go to consume all available memory (2GB) and be killed.

![image](https://github.com/newrelic/newrelic-ruby-agent/assets/129777267/3b869aa2-9d71-4c3e-8cfe-84fb537bd4d2)
[1] With HTTPX instrumentation disabled with `NEW_RELIC_INSTRUMENTATION_HTTPX=disabled`. Without the httpx instrumentation our application has a steady-state resident set memory of ~800MB.

## Expected Behavior
The New Relic Agent doesn't leak memory with it's HTTPX Instrumentation enabled. 

## Steps to Reproduce
Enable the HTTPX instrumentation. Make many HTTP requests using HTTPX and see RSS increase over time.  

## Your Environment

Ruby agent version: 9.6.0
Ruby version: 3.2.1
Rails version: 7.0.8
HTTPX version: 1.2.0

## Additional context
Similar Issue: https://github.com/newrelic/newrelic-ruby-agent/issues/2317

Relevant comment: 
> Hopefully that helps explain why memory usage might increase in the ruby agent, and some ways you can decrease how much memory the agent uses in your application.

I understand that the agent will use more memory to support HTTPX, but I would be surprised that it would use over a gigabyte more memory and grow at a constant rate over time instead of reaching a steady state.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by fallwith** [comment]
Hi @yuma-brendan,

Thank for you bringing this issue to our attention. We will investigate with a code audit and your reproduction instructions and determine our options for providing you with some HTTPX observability with a reasonable, small bump in overhead.

In the meantime for any other users encountering similar issues, the HTTPX instrumentation (on by default when HTTPX is detected) can be disabled either via an environment variable or a `newrelic.yml` config file setting:

**environment variable**
```shell
NEW_RELIC_INSTRUMENTATION_HTTPX=disabled
```

**newrelic.yml setting**
```yaml
instrumentation.httpx: disabled
```

**Comment by fallwith** [comment]
Hi @yuma-brendan,

## Findings and Hypotheses

We have audited the agent's HTTPX instrumentation and so far found it to be behaving as expected and in alignment with other HTTP libraries that are supported. There isn't any behavior we were able to reproduce that we can associate with a memory leak specific to HTTPX. We certainly welcome any repo or gist yourself or anyone else could put together to demonstrate the problem.

One thing I was able to reproduce is high memory consumption caused by a long running Sidekiq job that performs a large number of HTTP calls. Running the job will cause the agent to allocate memory to record various metrics for each call. Depending on how many calls are made, the memory allocated to keep track of each call's result can add up and gobble up available memory. Storing the agent's own internal spans in memory would be similar to retaining individual HTTP library response objects in memory and never releasing them until all requests had been completed.

What happens is that Sidekiq jobs are themselves instrumented by the agent and running a job will produce a New Relic transaction. Then any Ruby gem activity that is performed by the job and instrumented by the agent will produced segments that are nested underneath the parent Sidekiq transaction.

I was able to reproduce a steadily increasing consumption of memory by allowing a single Sidekiq job to run for a very long time and creating HTTPX requests in a loop. I then refactored the Sidekiq job to perform HTTP requests with Net::HTTP instead of HTTPX and observed identical behavior. This had given me some confidence that the issue might be generically New Relic Ruby agent related more than HTTPX instrumentation specific.

## Reproduction Steps Followed

First, create a new Rails app with HTTPX, Sidekiq, and New Relic:

```shell
export NEW_RELIC_LICENSE_KEY=(YOUR NEW RELIC LICENSE KEY)
export NEW_RELIC_AUDIT_LOG_ENABLED=true
mkdir test
cd test
bundle init
bundle add rails
bundle exec rails new demo --api --minimal --skip-git \
  --skip-action-mailer --skip-action-cable \
  --skip-javascript --skip-test  
cd demo
bundle add httpx
bundle add sidekiq
bundle add newrelic_rpm
bundle exec rails generate sidekiq:job repro
```

Next...

- Make sure a Redis server is available for Sidekiq to use
- Install a newrelic.yml file at `test/demo/config/newrelic.yml`
- Edit `app/sidekiq/repro_job.rb` and add the following line below the `# Do something` comment:

```ruby
# Do something
10_000.times do
  response = HTTPX.get('https://github.com')
  logger.info "HTTP #{response.status}"
end
```

Then enqueue the Sidekiq job and run Sidekiq:

```shell
bundle exec rails runner "ReproJob.perform_async('testing')"
bundle exec sidekiq
```

Monitor the `ruby` process(es) for changes in memory.

To test with Net:HTTP instead of HTTPX, add `require 'net/http'` at the top of `repro_job.rb` and then alter the loop like so:

```ruby
# Do something
10_000.times do
  response = Net::HTTP.get_response(URI('https://github.com'))
  logger.info "HTTP #{response.code}"
end
```

## Next Steps

I hope this info has been helpful.

Do please let us know if you are able to tell us more about your application and how it engages HTTPX without sharing any sensitive information or business logic.

And if you are able to share with us a self contained reproduction like the one I've shared here or modify this one, we'd be happy to do additional testing.

Here is the HTTPX instrumentation workflow:

- An HTTPX request is created while a New Relic transaction is already in progress
    - Transactions can be created by Rails controller method calls, Sidekiq jobs, etc.
- New Relic Ruby agent creates a segment to track the HTTP request
- New Relic Ruby agent hangs an on-response `proc` on the HTTPX request to finish the segment
- The HTTP request completes. The HTTPX request object should soon be garbage collected
- Once the New Relic transaction completes, the HTTPX instrumentation segment should soon be garbage collected

This logic lives at [lib/new_relic/agent/instrumentation/httpx/instrumentation.rb](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/httpx/instrumentation.rb). If anything suspicious jumps out regarding that workflow or the code, we welcome feedback on it!

**Comment by yuma-brendan** [comment]
@fallwith Thanks so much for the in depth work to reproduce this. It makes me happy that we chose New Relic. 

Some more specifics about our app:

- We use HTTPX for external service integrations where they don't supply a ruby API.  
- We have a lot of external integrations that are called very frequently. 
- We have some long lived jobs, but we have them segregated on to different workers. 
- Our low-latency workers was have jobs that last at most 3 minutes, but more often less than a few seconds.  These workers were affected.


I've put it on my list of things to look into further. I will keep you posted.

**Comment by fallwith** [comment]
Thanks for the info, @yuma-brendan. I set up some additional testing that involved short lived activity with only a single HTTPX call being made per New Relic transaction. So a single Ruby VM is kept running while it iterates over lots of individual transactions and then memory is looked at over time.

My high level findings from this additional testing are:

- Having the HTTPX instrumentation enabled definitely requires more memory, but not a troubling amount that would lead to either a crash or a much larger more costly cloud instance to accommodate.
- None of the additional memory consumed was "leaked" per se. It was all still well within the control of the Ruby VM and able to be reclaimed and repurposed as the need arose.

Some notes on testing...

1. To be able to make as many HTTPX requests as possible, I spun up a dummy WEBrick server with this code:

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'webrick'

class FakeServlet < WEBrick::HTTPServlet::AbstractServlet
  RESPONSE_BODY = "Success\n"
  TEXT_PLAIN = 'text/plain'

  def do_GET(_request, response)
    # query hash is accessible via request.query
    # request path is accessible via request.path

    response.status = 200
    response.content_type = TEXT_PLAIN
    response.body = RESPONSE_BODY
  end
end

class FakeServer
  DEFAULT_PORT = 80

  def initialize(port = nil)
    port ||= DEFAULT_PORT
    @server = WEBrick::HTTPServer.new(Port: port)
    @server.mount '/', FakeServlet
    @server.start
  end
end

port = ARGV[0].to_i unless ARGV.empty?
FakeServer.new(port)
```

2. I used `benchmark`, `benchmark/ips`, system `ps`, and system `Activity Monitor` to measure resource usage.

3. I hypothesized that either the agent's monkeypatching of HTTPX or use of an on-response callback might be problematic, so I set up a reproduction of these elements in a standalone (no New Relic agent involved) context with this code. But neither the monkeypatching nor the callbacks seemed to have a negative impact.

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'httpx'

module PrependMe
  def send_requests(*requests)
    send_with_callback(*requests) { super }
  end

  def send_with_callback(*requests)
    requests.each { |r| prep_request(r) }
    yield
  end

  def prep_request(request)
    request.on(:response) { request_finish_callback.call(request) }
  end

  def request_finish_callback
    proc do |request|
      response = @responses[request]
      raise "Could not find a response for >>#{request}<<" unless response
      raise "Could not connect: >>#{response}<<" if response.is_a?(::HTTPX::ErrorResponse)

      puts "Callback is processing response id #{response.object_id}..."
    end
  end
end

class Tester
  COUNT = 100
  URL = 'http://localhost:1138'

  def test
    COUNT.times do
      response = HTTPX.get(URL)
      raise response.error if response.error
    end
  end
end

HTTPX::Session.prepend(PrependMe)
Tester.new.test

puts 'Monkey-patched with callbacks'
puts `ps -o rss -p #{$$}`
```
4. For all tests involving the agent, I performed the same tests against the Net::HTTP library. Amusingly, Net::HTTP would error out more often when iterating over 100,000 requests, but beyond that resource allocation for both libraries looked the same. This could of course still mean that multiple HTTP client instrumentations in the agent are problematic.

In summary:

- I have not yet been able to reproduce resource allocation issues that would suggest that the agent's HTTPX instrumentation involves more overhead or any other con than the agent's other HTTP client instrumentations.
- When I do reproduce normal instrumentation overhead, that overhead does not involve leaking - just regular memory allocation that can be reclaimed and repurposed after New Relic has finished reporting on activity.

Of course my testing has involved fairly simple scripts and web apps and we agent maintainers are still very open to the possibility that a problem does exist with either the HTTPX instrumentation or the agent itself.

Whenever you yourself or any other HTTPX user has time to put together a reproduction or advise our team on additional things to try, we'll be happy to investigate farther.

**Comment by fallwith** [comment]
Hi @yuma-brendan,

Have you had a chance to look at this one any further on your end? No worries if not, because if you simply want things running smoothly and don't especially need metrics for the HTTPX calls, you've already got a great solution in disabling the HTTPX instrumentation.

If you end up producing a reproduction script that can demonstrate an issue, we'd be delighted to take a look. You're welcome to use [this example gist](https://gist.github.com/fallwith/9f550bb75da16158f27028759551735e) as a template.

**Comment by yuma-brendan** [comment]
Hey @fallwith I think we can close the issue. We're still seeing this, just at a much reduced rate. My hunch is that we have other middleware that is holding on to objects for a very long time and New Relic's HTTPX instrumentation was multiplying the effect of that. More debugging on our end to do 🤷 

Thank you so much for your help here :)
