### ISSUE TITLE
add_method_tracer no longer working for instrumenting class methods via an included module

### ISSUE THREAD

**Issue by okcscott** [newrelic/newrelic-ruby-agent#2458]
## Description

I have a project that I am upgrading and as part of I need to bump `newrelic_rpm` from version 6 to 9. Part of our code was that utilizing `add_method_tracer` is no longer working in the new version. I know a lot changed in between those version, and I'm looking for a little guidance on how to get this working again.

We have a simple module that we include in all of our service objects that allow us to do `ServiceObject.call('arg')` it looks like this

```
require 'new_relic/agent/method_tracer'

module ProjectName
  module ServiceObject
    def self.included(base)
      ClassMethods.class_eval do
        extend ::NewRelic::Agent::MethodTracer
        add_method_tracer :call, base.name
      end
      base.extend ClassMethods
      super
    end

    module ClassMethods
      def call(*args)        
        new(*args).call
      end
    end
  end
end
```

I also have a spec that used to pass, that looks like this

```
class TestClass
  include ProjectName::ServiceObject

  def initialize(foo)
    @foo = foo
  end

  def call; end
end

RSpec.describe ProjectName::ServiceObject do
  it 'extends correctly' do
    TestClass.call('test')
    expect(TestClass.singleton_class.traced_method_exists?(:call, 'TestClass')).to be true
  end
end
```

It appears that `traced_method_exists?` was changed to `method_traced?`. I've tried quite a few things, but they are all still returning `false` when my test calls `method_traced?`. 

Thoughts?

## Expected Behavior
I would expect `TestClass.singleton_class.method_traced?(:call)` to return `true` in my spec.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 

## Your Environment
ruby 3.1.2
rails 7
newrelic_rpm 9.7.1

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by fallwith** [comment]
Hi @okcscott,

We appreciate being a part of your project upgrade! Hopefully we can help get the RSpec testing on track with the latest version of the agent.

Everything that you are doing with `ProjectName::ServiceObject::ClassMethods` and `TestClass` is perfect, and invoking `TestClass.call` will indeed result in a New Relic traced method being invoked. So no changes needed there, we just need to figure out how to have RSpec verify that the method is traced.

Your thinking of using `method_traced?` as the replacement for `traced_method_exists?` makes a lot of sense. Unfortunately it doesn't work from classes that have extended the module responsible for calling `add_method_tracer`. When `add_method_tracer` is called, the agent memoizes a new Ruby module with a `@_nr_traced_method_module` instance variable belonging to the calling object. The module has one method of the same name defined for every method that has been set up for tracing. When `method_traced?` is called, that instance variable is looked for and then a `method_defined?` check is performed against the module. Using RSpec, we can see that this won't work for `TestClass` but instead will only work on `ProjectName::ServiceObject::ClassMethods`:

```ruby
# Ruby

TestClass.singleton_class.method_traced?(:call)
  # => false
TestClass.method_traced?(:call)
  # => false

ProjectName::ServiceObject::ClassMethods.method_traced?(:call)
  # => true
mod = ProjectName::ServiceObject::ClassMethods.instance_variable_get(:@_nr_traced_method_module)
mod.method_defined?(:call)
  # => true
```

If you want to, you can have an RSpec expectation focus on `ProjectName::ServiceObject::ClassMethods` to confirm that the `:call` method is set up for tracing and then verify that `TestClass` has brought in the module:

```ruby
# RSpec approach 1

expect(ProjectName::ServiceObject::ClassMethods.method_traced?(:call)).to be true
  # => true
expect(TestClass.include?(ProjectName::ServiceObject)).to be true
  # => true
```

If you'd prefer to work directly with the `TestClass` class, one idea would be to confirm that the `:call` method for that class has indeed been redefined by New Relic:

```ruby
# RSpec approach 2

expect(TestClass.method(:call).source_location.first).to match(/method_tracer/)
  # => true
```

If `TestClass.call` has been defined by New Relic, the source location will successfully include the 'method_tracer' string. If it had not been set up for tracing by New Relic, the source location would point to original file that defined the `:call` method instead and the RSpec expectation would fail.

Hopefully one of these two approaches listed here that are generating `true` RSpec expectation results will be helpful in getting the RSpec tests working again. Otherwise we'd be happy to explore further options with you, investigate anything that you feel might be a bug, or consider any related feature requests you may have. Please let us know either way.

**Comment by fallwith** [comment]
Hi @okcscott,

I'm going to go ahead and close this one now. Feel free to reopen it or create new issues if you have any other things that crop up during your upgrade process.
