### ISSUE TITLE
AWS: End to end testing for dynamoDB

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-ruby-agent#2588]
Test 4 scenarios end to end for dynamoDB instrumentation

**Comment by kaylareopelle** [comment]
I met with André today to get the testing environment set up for Ruby. Unfortunately, we weren't able to successfully complete the setup for Cloud Watch Metric Streams because of an error, which has been reported to the correct teams.

I should have the information I need to finish Cloud Watch Metric Stream set up when the error is resolved.

Fortunately, Ruby is already set up for API Polling, and now I know where we need to go to look for the related entities. I may need one more sync with André to finish the knowledge transfer.

**Comment by kaylareopelle** [comment]
This issue is blocked until we can get Cloud Watch Metric Stream set up for our account. The problem is under review by the Infra UI team.

**Comment by kaylareopelle** [comment]
We got through the initial Cloud Watch Metric Stream setup, but we are still not seeing data ingested for our account. I'm troubleshooting this on May 7 with André.

**Comment by kaylareopelle** [comment]
Testing passed! https://newrelic.atlassian.net/wiki/spaces/INST/pages/3307634814/AWS+DYNAMO+DB+TABLE#Ruby-Agent
