### ISSUE TITLE
[Spike] Support Rails 7.2

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2650]
[rails/rails milestone for 7.2](https://github.com/rails/rails/milestone/83)

estimated release June 2024

Can be accessed using [7-2-stable](https://github.com/rails/rails/tree/7-2-stable)

**Comment by praveen-ks** [comment]
Hi @kaylareopelle 

When can we expect Rails 7.2 support.

**Comment by fallwith** [comment]
Hi @praveen-ks, the latest published New Relic Ruby agent gem is expected to be fully compatible with Ruby on Rails v7.2 once it comes out of beta. We actually tested v7.2 in alpha for months back when Rails EDGE pointed to v7.2 instead of v8.0 and didn't encounter any problems. And we have recently been testing the v7.2 beta builds available from Rubygems.org and everything is working great.

This GitHub issue served to make sure we formalize v7.2 testing with our CI system, and to do a final pass over the v7.2 changelog to make sure we are instrumenting everything. Both of those efforts are now complete.

If you encounter any issues or new functionality that isn't instrumented once Rails v7.2 is released, do please let us know here with a bug report or feature request, but we currently believe that our existing gem version is good to go.

**Comment by fallwith** [comment]
- New v7.2 specific CI environment added (now that Rails EDGE no longer points to v7.2 but to v8.0)
- Audited v7.2 CHANGELOG and code base. Added support for 4 additional notifications, but those all predated v7.2
