### ISSUE TITLE
Update `darwin` environment report output

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#2775]
Expected: `darwin`, Received: `darwin22`/`darwin23`

**Comment by kaylareopelle** [comment]
@prateeksen - Getting `darwin` plus the version (ex. `darwin22`, `darwin23`) seems like valuable context. 

Why would you like the version number removed?

**Comment by prateeksen** [comment]
@kaylareopelle IAST SaaS engine checks for the versions of the OS/Frameworks/Dispatcher and mark the applications on the customer UI whether those are supported by IAST or not. In case of Mac they have check on 'Mac OS X' or 'darwin'. When ruby APM agent sends `darwin` plus the version (ex. `darwin22`, `darwin23`) validation fails and IAST version checker shows that application is not supported by IAST. Adding `darwin22`, `darwin23` is not feasible as every newer versions will need to be added manually in future.
Although, I can ask IAST SaaS team if they can check `darwin*` instead of `darwin` but I find sending OS name only in os name field more better as [OS version](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/environment_report.rb#L69) is already there as a separate field.

**Comment by kaylareopelle** [comment]
Hi @prateeksen, thanks for the clarification, I didn't realize there was an OS version field. This update also gets us closer to the OS attributes for OpenTelemetry. 

I appreciate you catching the issue and opening a PR for the change!
