### ISSUE TITLE
Unit tests coverage report artifacts are not stored in github actions

### ISSUE THREAD

**Issue by prateeksen** [newrelic/newrelic-ruby-agent#2786]
Unit tests coverage report artifacts are not stored in github actions.
My prime guess is that this issue could has been arrived while updating the artifact upload plugin in [this commit](https://github.com/newrelic/newrelic-ruby-agent/commit/c491bf495860c760c3c78cc8370345027cba63d2) as plugin has changed the regex matching mechanism.
Earlier I had also faced a similar issue while upgrading the upload artifact in csec-ruby-agent and here are the PR links for the solution implemented.
[#78](https://github.com/newrelic/csec-ruby-agent/pull/78) & [#79](https://github.com/newrelic/csec-ruby-agent/pull/79)

**Comment by kaylareopelle** [comment]
Thanks for raising this, @prateeksen! I'm going to remove the `bug` label from this issue because it's a bug related to the CI and not the agent itself, and add `technical debt` instead.

**Comment by hannahramadan** [comment]
Hi @prateeksen! I'm looking into this and am having trouble spotting the issue. On the Ruby agent side, I am seeing results uploaded for Infinite Tracing, Unit Tests, and Multiverse (we have a few more testing groups than csec). Here is an [example](https://github.com/newrelic/newrelic-ruby-agent/actions/runs/10409640209) run. Because we have these three separate groups, we then stitch the results together and upload a final artifact named `coverage-report-combined`, which is at the top of artifacts list in the example. 

Good note on the upgrade from v3 to v4 of `actions/upload-artifact`! We also recently upgraded a few of our CI actions ([PR](https://github.com/newrelic/newrelic-ruby-agent/pull/2787)) and had to make the same changes of creating dynamic/unique artifact names.

**Comment by prateeksen** [comment]
Hi @hannahramadan Thanks for the update. I again checked the link you provided and I see that artifacts are saved in combined report, last time I checked I didn't found the a artifacts in combined report and hence reported this issue, Maybe I have seen some incomplete build run. If we have the artifacts saved and seeing expected behaviour you can close the issue. Thanks.
