### ISSUE TITLE
9.14 - ArgumentError with rdkafka integration

### ISSUE THREAD

**Issue by krisdigital** [newrelic/newrelic-ruby-agent#2879]
## Description
After the update from 9.13 to 9.14 there is an error

```
ArgumentError • vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.14.0/lib/new_relic/agent/instrumentation/rdkafka/prepend.rb:58
ArgumentError: wrong number of arguments (given 1, expected 0)
```

## Expected Behavior
No bugs...

## Steps to Reproduce
Just install...

## Your Environment
Using 'karafka', '2.4.7' with ruby 3.3.5 and Rails 7.1.3.4

## Additional context
-

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by tannalynn** [comment]
Hello @krisdigital 
Thank you for bringing this to our attention! We added instrumentation for the `rdkafka` gem. It looks like this is happening because version number differences between `rdkafka` and `karafka-rdkafka` that introduced a specific change to args on the consumer/producer methods. I was able to reproduce the same error using certain versions of karafka-rdkafka, so I've added an additional check that should allow the correct instrumentation to be installed. This solved the error for me, and you can test this branch with this:
```
gem 'newrelic_rpm', github: 'newrelic/newrelic-ruby-agent', branch: 'rdkafka_karafka_bugfix'
```

**Comment by krisdigital** [comment]
@tannalynn Thank you for your quick reply and fix! We will check with the next version!

**Comment by mensfeld** [comment]
Hey, maintainer of rdkafka and karafka-rdkafka here :wave: 

sorry for the issue. I am working on aligning their versioning as well as unifying them into one repo (rdkafka-ruby). However, this will still take time because of some major differences in error handling between them. Meanwhile do not hesitate if anything is off or if you have any issues :pray:

**Comment by tannalynn** [comment]
The fix for for this has been merged and will be included in the next release. Thank you!
