### ISSUE TITLE
Update yajl-ruby instrumentation

### ISSUE THREAD

**Issue by rachelleahklein** [newrelic/newrelic-ruby-agent#401]
The Ruby agent is known to support up to version 1.3.x of the yajl-ruby gem. We would love your help in making sure our instrumentation works with the latest version.

For guidance on how to proceed, see our [Guide to Updating Instrumentation](https://github.com/newrelic/newrelic-ruby-agent/wiki/Guide-to-Updating-Instrumentation), and please let us know if you have any questions not covered there.

**Comment by creaturenex** [comment]
Hello,

This is the first time I am contributing to open source. I wanted to see if I could update the envfile to test the new version of "yajl-ruby" v 1.4.1. When following the directions [Guide to Updating Instrumentation](https://github.com/newrelic/newrelic-ruby-agent/wiki/Guide-to-Updating-Instrumentation) the first step says you can test your changes using `rake:test multiverse[name_of_suite]`. This command is not working on my end I wasn't sure if this was a typo. I can get `rake test:multiverse` to work and it run all the test suites. When I try to run `rake test:multiverse[yajl] or rake:test multiverse[yajl]` it get the following error `zsh: no matches found: test:multiverse[yajl]`.

I wanted to know if there is something on my end that I am doing incorrectly. I am testing on a linux machine, elementary os, unbuntu based, using ohmyzsh, with a hyper terminal and using RVM. Let me know if you need additional information.

**Comment by amhuntsman** [comment]
@creaturenex Hello, and thank you for your contribution!

If you're using zsh, you'll need to escape the square brackets in that command:

    rake test:multiverse\[yajl\]

**Comment by creaturenex** [comment]
@amhuntsman Thanks I did not know I had to do that! lesson learned.
I hate to bother but now I am getting, I ran `rake test:multiverse\[yajl\]` & `bundle exec rake test:multiverse\[yajl\]`, RVM is current in Ruby 3.0.0.
```ruby
SKIPPED "/home/oscar/Projects/Github_repos/newrelic-ruby-agent/test/multiverse/suites/yajl"
: Yajl not supported for JRuby or 2.4
```
I see the Envfile in  `newrelic-ruby-agent/test/multiverse/suites/yajl` has the statement. I assumed maybe incorrectly that the test would load the required gems. 
```ruby
suite_condition("Yajl not supported for JRuby or 2.4") do
  RUBY_PLATFORM != 'java' && RUBY_VERSION < '2.4.0'
end
```

**Comment by amhuntsman** [comment]
@creaturenex Ruby 2.4+ is not suppored in the yalj-ruby gem prior to version 1.2.2, so this Envfile likely needs updating. You can look at other Envfiles to see examples of conditionals on `RUBY_VERSION`, such as

https://github.com/newrelic/newrelic-ruby-agent/blob/dev/test/multiverse/suites/capistrano2/Envfile

Then you can test against newer Ruby versions accordingly.

**Comment by creaturenex** [comment]
awesome I will give a go and report back thank you so much for the help.

**Comment by creaturenex** [comment]
I was able to get a passing test using `rake test:multiverse[yajl]` after adding an if statement and adding the `#{ruby3_gem_webrick}` as ruby 3.0. no longer has webrick-gem bundled.

Also the suite_condition would prevent the test from running so that was also wrapped in an if statement. Please review if any issues arise. 

I read the yajl_test.rb file and saw the comment that `require 'yajl/json_gem'` overrides your JSON marshalling. Reading the [yajl documentation](https://rdoc.info/github/brianmario/yajl-ruby#json-gem-compatibility-api) it looks like `require 'yajl/json_gem'` just replaces  `require 'json'`. I was able to get a passing test by using `require 'json'` in the yajl_test file instead of `require 'yajl/json_gem'` on line 8 and by using `require: ['yajl', 'json']` in the Envfile on line 10. Those changes were reverted back to `'yajl/json_gem'` and continued to work.

The test currently pass as I have it but I did have some follow up questions like are the following code required?

- `json_gems = ['~> 2.3.0', '~> 2.4.0', '~> 2.5.0']`
  - Do I need to specify json version? I see require 'yajl/json_gem'
    This example is from suite/json/Envfile.
  - Not sure if my comment above corrects the issue
- `instrumentation_methods :chain, :prepend`
  - Most suite that where updated recently have this.
- `rack_test_version = RUBY_VERSION < "2.2.0" ? "< 0.8.0" : ">= 0.8.0"`
  - Some suite that where updated recently have this.
