### ISSUE TITLE
Update documentation about configuration agent 

### ISSUE THREAD

**Issue by Ivan-Skotsyk** [newrelic/newrelic-ruby-agent#409]
From ruby agent configuration doc (https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration) 

When running the Ruby agent in a Rails app, the agent will use the Rails environment (RAILS_ENV or RAILS.env, depending on the version of Rails) to determine the application environment and which section of the newrelic.yml to use. **You can still use the NEW_RELIC_\* environment variables to take precedence over the other settings in your newrelic.yml config file, but NEW_RELIC_ENV will not be used to determine the application environment**.

But really NEW_RELIC_ENV determine the application environment: https://github.com/newrelic/newrelic-ruby-agent/blob/c9203be16af3468f275bbde078dc2805ad878655/lib/new_relic/control/frameworks/rails.rb#L15

It's confusing and takes some time to find and fix the issue if you follow docs.

**Comment by rachelleahklein** [comment]
Hi @Ivan-Skotsyk - thanks so much for pointing this out. It seems clear that back when the `NEW_RELIC_ENV` setting was introduced for Rails environments back in [version 4.1.0](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CHANGELOG.md#v410), it was meant to be used instead of the Rails environment when both are present. I'm not sure why our documentation reflects the opposite; sorry for the confusion.

We'll get that fixed right away. Again, thanks!

**Comment by rachelleahklein** [comment]
The documentation (as linked in the original post) is updated so I'm closing this ticket, but please feel free to reopen if you've got any clarifications to make. Again, thanks!
