### ISSUE TITLE
Latest version not published to rubygems

### ISSUE THREAD

**Issue by dorongutman** [newrelic/newrelic-ruby-agent#504]
## Description
Version 6.14.0 was released 4 days ago, but the newest version according to rubygems.org is 6.13.1, so version 6.14.0 can't be installed using bundler or gem install (at least not in the default way)

## Expected Behavior
Version 6.14.0 to be available in rubygems.org

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
NA

## Steps to Reproduce
Go to https://rubygems.org/gems/newrelic_rpm

## Your Environment
NA

## Additional context
NA

**Comment by mwlang** [comment]
@dorongutman We're actually in a pre-release state at the moment with some additional vetting of the gem to ensure it's ready for production use.  Hang tight because it should be officially published no later than Friday, assuming all goes well (and there's every indication it's on track to releasing).

**Comment by tannalynn** [comment]
After completing our internal pre-release verification, 6.14.0 has now been released! 
You should now be able to install 6.14.0 from rubygems.
