### ISSUE TITLE
Infinite Recursion of net/http

### ISSUE THREAD

**Issue by willcosgrove** [newrelic/newrelic-ruby-agent#530]
## Description
I think I've tracked back our problem to the same one that was fixed here: #511 
We do not use the airbrake or rack-mini-profiler gems. We do however use both Scout and Honeybadger, either of which I suspect could be monkey patching net/http like airbrake or rack-mini-profiler did.

## Expected Behavior
Net/http requests would be unaffected.

## Steps to Reproduce
Run a rails app with the newrelic_rpm gem and the scout gem or the honeybadger gem.

## Your Environment
I noticed this when I upgraded to 6.14.0. I reverted back to the previous version we were using: 6.11.0.365 and the issue went away.

**Comment by tannalynn** [comment]
Thank you for bringing this to our attention @willcosgrove. We've seen a few gems already that are incompatible with the updated prepend instrumentation due to monkey patching, and it seems there are more and more popping up.

For now, while this behavior is defaulted to true, you can disable this by adding this to your newrelic.yml in version 6.14.0:
```prepend_net_instrumentation: false```

I think the best solution going forward for us, for now, will be to default this option to false, so that our old instrumentation is used by default. This is will prevent unexpected compatibility issues with various gems that have not yet moved away from monkey patching.
