### ISSUE TITLE
missing postgres stats after upgrade to 6.15.0

### ISSUE THREAD

**Issue by gsar** [newrelic/newrelic-ruby-agent#561]
## Description

The Databases area is no longer showing any stats for postgres queries since upgrading from 6.14.0 to 6.15.0. We also upgraded to rails 6.1.1 from rails 6.0.3.4 at the same time.  Everything went silent after the Feb 3rd deploy that introduced both upgrades.

![image](https://user-images.githubusercontent.com/6981812/106953842-bbd97000-66e7-11eb-8c6d-331bb1f4a903.png)

I also noticed that all database queries look different, the table names are missing, screenshot comparison of a typical query below:

![image](https://user-images.githubusercontent.com/6981812/106954143-3904e500-66e8-11eb-9b2a-83b7658a7ab7.png)

vs

![image](https://user-images.githubusercontent.com/6981812/106954267-6356a280-66e8-11eb-955a-86dc5b90624d.png)

The changelog for 6.15.0 doesn't mention any activerecord configuration changes, hope I'm not missing a configuration step.

## Expected Behavior

Postgres stats should be shown.

## Your Environment

ruby 2.7.2
rails 6.1.1
newrelic_rpm 6.15.0

**Comment by tannalynn** [comment]
Hello, @gsar 
Thank you for bringing this to our attention.
Looking at this, I suspect this may be related to the rails upgrade to 6.1. 
We added rails 6.1 to our test suite and everything is working as expected there, however it's possible that some things maybe changed in 6.1 that are not covered by our current test cases. We will need to spend some time digging deeper on 6.1 and experiment with it to confirm our test cases are accurately reflecting how activerecord 6.1 is working. 

I do have a couple questions about how you guys are using 6.1, to help guide us in our investigations. 
Are you setting `legacy_connection_handling` to false?
Are you utilizing multiple connections?
Any other changes or new features of rails that you guys have started using?
Thank would be very helpful for us to track this down.

Apologies for the delayed response, thank you for your patience.

**Comment by motionless** [comment]
We have the same observation/problem after upgrading to Rails 6.1

Environment:
Rails version:	6.1.3
NewRelic gem: 6.1.5
Ruby version:	2.7.1

legacy_connection_handling is not set.

We use multiple connections trough - ActiveRecord::Base.connected_to for a few specific queries. The behavior is consistent throughout the whole application.

The queries are showing up as `ActiveRecord` instead of `Postgres`.
This wouldn't be a big deal in the long run, even though it is inconvenient at the moment.

The problem occurs when guessing the SQL statements.
![image](https://user-images.githubusercontent.com/491532/109499685-82e9ac80-7a95-11eb-8a3a-472ef488b5ca.png)


___
With Rails 6.0
![image](https://user-images.githubusercontent.com/491532/109499208-df989780-7a94-11eb-9850-f4ca6db81336.png)
___
With Rails 6.1
![image](https://user-images.githubusercontent.com/491532/109499243-e921ff80-7a94-11eb-9c76-541b4e7ce301.png)
___

Let me know if I can help somehow with additional information.

**Comment by gsar** [comment]
@tannalynn sorry for the delayed response.

We are not setting/changing `legacy_connection_handling`. We have a rather plain vanilla rails config with not much customization.  However, we use the `sqreen` and `airbrake` gems, which I know have resulted in conflicts in the past.

We have the standard `config/puma.rb` setup to have each worker instance start a new db connection with:

``` ruby
on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

In `config/application.rb` we set `config.load_defaults 6.0`.

Everything else is pretty much out of the box.
