### ISSUE TITLE
Rails 5 + Rack + Rack Cors + Puma produces "can't add a new key into hash during iteration" Errors

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#573]
## Description
Error: can't add a new key into hash during iteration
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:79:in `set_header'

We're fighting with this persistent and long-standing error again on production with New Relic and Rack when deploying using Puma with multiple threads in Rails. It appears that the env hash isn't atomic and Rack (or rack-cors) attempts to add a key while New Relic iterates over it internally leading to a somewhat rare but breaking error. It usually takes 20-30 minutes, and the frequency increases based on number of threads, especially when not using workers. This happens on any route at random intervals.

There are some related topics I’ve found online but no public solutions, and the only solution I’ve found is either to not use New Relic at all or to set the thread count to 1 and compensate for that concurrency slack by increasing the number of workers that Puma uses. I’ve spoken to an engineer on another project using a similar setup but they don’t seem to be affected by this issue, possibly due to the fact they’re using Rails 4 and outdated gems, or that they wrap their rack-cors implementation in Grape middleware.

There seem to be [other tickets](https://discuss.newrelic.com/t/ruby-runtime-error-cant-add-a-new-key-into-hash-during-iteration/77571/10) out there referring to this issue as well, if any relevant communication can be relayed from those, that'd be appreciated. 

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce

This can be reproduced by deploying a Rails app with Puma, that has New Relic set up, and using Rack and / or rack-cors. Disable workers and increase number of threads to 16+, the higher the number of threads the more frequently this error will occur.

## Your Environment

Our gem versions are:
rails 5.2.4.4
rack 2.2.3
rack-cors 1.1.1
newrelic_rpm 6.15.0
puma 5.2.1

## Additional context
* [New Relic Explorers - Ruby runtime error: “can’t add a new key into hash during iteration”](https://discuss.newrelic.com/t/ruby-runtime-error-cant-add-a-new-key-into-hash-during-iteration/77571)
* [Stack Overflow - RuntimeError: can't add a new key into hash during iteration in Rack](https://stackoverflow.com/questions/47768547/runtimeerror-cant-add-a-new-key-into-hash-during-iteration-in-rack)
* [nattfodd/stack.txt](https://gist.github.com/Nattfodd/e513122400b4115a653ea38d69917a9a)

**Comment by jeremyhaile** [comment]
We are experiencing this issue with:

rails 5.1.7
rack 2.0.8
rack-cors 1.0.6
newrelic_rpm 6.15.0
puma 4.3.6

**Comment by wyhaines** [comment]
The problem here is that the ENV variable contains a hash-like entity which, like all Ruby Hashes, is not modifiable while it is being iterated.

The only viable fix, short of replacing ENV in Ruby with a more concurrency-friendly structure, is to change how the NR code does the iteration.

In doing a survey of the ruby agent code, there is actually only a single location that I can find where a direct iteration over the ENV hash occurs:

https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/connect/request_builder.rb#L52

There are options to replace this, depending on how performant it needs to be versus how resistant to race conditions (i.e. the environment being changed underneath it while it is iterating).

My hunch is that since ENV typically changes very little or not at all during the course of regular program execution, performance trumps absolute integrity. I can make a PR for you that will hopefully address this problem.

**Comment by wyhaines** [comment]
I have a fix that I did on stream. I'll send the PR tomorrow. I don't have an app/setup that I can actually test it on, though, so I may need to collab with someone else in the team to actually test it.

**Comment by wyhaines** [comment]
Quick update.  I just realized that with FutureStack, I forgot to actually create this PR.  You'll have it today.

**Comment by evanjuneau** [comment]
Thank you for your fix @wyhaines , but we are still encountering this error using newrelic_rpm 7.2.0 and a similar gem configuration which to my understanding should have fixed this issue. I can provide an updated stack trace if needed, but it's ultimately the same concurrency issue (changing the ENV variable during iteration).

**Comment by raman162** [comment]
I can also confirm that this issue persists with newrelic_rpm 7.2.0. The easiest way I was able to reproduce in my local test environment was to do the following:

1. setup endpoint with bad code that will raise an error. Note that we did not explicitly raise the error, the code was just not ideal. 
2. setup another endpoint that returns a simple html page
3. perform simple load test on both endpoints simultaneously

When reviewing logs, we noted that the simple endpoint that returned the html page occasionally  has iteration error.

The fix we did for our project was to prevent/explicitly rescue these errors in our app. I can imagine this issue is much more prevalent with apps that process a high volume of requests per second.

**Comment by wyhaines** [comment]
@evanjuneau @raman162 Can you tell me which versions of Rack you are both using? I am trying to figure this out, and it would be helpful to know if you are both on versions that are at or around the originally reported version of 2.2.3, or if you are on different versions?

**Comment by raman162** [comment]
Hi @wyhaines we are using rack 2.2.3 as well

**Comment by wyhaines** [comment]
@raman162 Thank you. I am trying to establish a minimal test case to reliably reproduce the problem. There have been some architecture changes in the Rack Request object between 2.2.3 and the current version, so I wanted to make sure that I was starting with what you all are currently using.

**Comment by raman162** [comment]
Thanks for your time and attention for looking into this @wyhaines. It is greatly appreciated.

**Comment by evanjuneau** [comment]
I apologize for the late response. I am the original reporter for this issue through New Relic’s help section, so I want to provide a proper update with a newer stack trace using newrelic_rpm 7.2.0 attached. I’m very grateful you’re looking into this, and thank you so much for your time @wyhaines!

Here’s an updated list of possible relevant gems and their versions:

rails 5.2.6
rack 2.2.3
rack-cors 1.1.1
newrelic_rpm 7.2.0
puma 5.4.0

The easiest way I've found to test it is to bump up the number of minimum / maximum threads and don’t use workers in Puma. Then hit a few endpoints simultaneously as @raman162 mentioned. You should encounter a similar error occasionally. I should also mention that our product is using Rails in an API-only context (Rails::API).

I have also looked into our stack trace a bit, and although I do see iteration over the ENV variable explicitly (actionpack-5.2.6/lib/action_dispatch/middleware/request_id.rb:26) where it's setting the request ID in the headers hash, I'm unsure if this is caused by New Relic somewhere deeper in the stack trace specifically, or if the root of the issue is more on the side of Rails and New Relic is handling this error correctly or erroneously rescuing early. Once again, thank you!

`RuntimeError: can't add a new key into hash during iteration

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:79:in `set_header'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/http/request.rb:299:in `request_id='

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/request_id.rb:26:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/executor.rb:14:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/static.rb:127:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/puma-5.4.0/lib/puma/configuration.rb:249:in `call'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/puma-5.4.0/lib/puma/request.rb:77:in `block in handle_request'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/puma-5.4.0/lib/puma/thread_pool.rb:340:in `with_force_shutdown'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/puma-5.4.0/lib/puma/request.rb:76:in `handle_request'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/puma-5.4.0/lib/puma/server.rb:440:in `process_client'

	/root/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/puma-5.4.0/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
`

**Comment by sasharevzin** [comment]
I can confirm that it still happens
