### ISSUE TITLE
Faraday support in HTTP Client Tracing

### ISSUE THREAD

**Issue by waissbluth** [newrelic/newrelic-ruby-agent#610]
It would be great if Faraday ([one of the more popular ruby HTTP clients](https://blog.bearer.sh/top-ruby-http-client-gems/)) was supported out-of-the-box by the NewRelic agent.

### Feature Description
Automatic instrumentation of Faraday requests, like it happens for other HTTP clients. According to [these docs](https://docs.newrelic.com/docs/agents/ruby-agent/features/http-client-tracing-ruby), any client that uses `Net::HTTP` as its underlying adapter should work automatically, but this has not been my experience.

### Describe Alternatives
There are a couple of gems in the wild that do this. Most notably, [newrelic-faraday](https://rubygems.org/gems/newrelic-faraday/versions/0.7.0), which has not received updates recently and declares dependencies that are incompatible with the latest faraday and newrelic agent. [This fork](https://github.com/mapdwell/newrelic-faraday) addresses that and has been working fine for us.

### Additional context
This issue might be related: https://github.com/newrelic/newrelic-ruby-agent/issues/557

### Priority
Really Want

**Comment by mwlang** [comment]
@waissbluth Historically, Faraday hasn't been included because of the referenced gem's existence.  However, it does look like the project has gone dormant, so would be a good feature request to consider adding native support for.

I am curious about what the fail point is on `Net::HTTP` is in your experience.  We should address this issue as well.

**Comment by waissbluth** [comment]
Hi @mwlang thanks for looking into this so quickly.

I looked into the `Net::HTTP` bit and it seems that reporting for Faraday via `Net::HTTP` is in fact working for me, but I was confused by how the "Service Map" and "External Services" tabs work in APM. Essentially, the Faraday requests are showing up in the External Services tab, but they only show up in the Service Map if there has been activity for that service within the last 30 minutes. That is my assumption at least, since the timeframe is not customizable there.

I am still curious about the benefit of `newrelic-faraday` then. Is it only to cover other adapters? If so, feel free to close the issue since I believe the investigation above resolves it.

Thanks

**Comment by mwlang** [comment]
I think you may have it right about service maps and timeframe of the external calls.
The main thing I see newrelic-faraday doing is recording additional metrics:

[source](https://github.com/mapdwell/newrelic-faraday/blob/master/lib/newrelic_faraday/instrumentation.rb#L17-L26)

```ruby
      def run_request_with_newrelic_trace(method, url, params, headers, &block)
        newrelic_host = parse_host_for_newrelic url
        metrics = ["External/#{newrelic_host}/Faraday::Connection/#{method}", "External/#{newrelic_host}/all", "External/all"]
        if NewRelic::Agent::Transaction.recording_web_transaction?
          metrics << "External/allWeb"
        else
          metrics << "External/allOther"
        end
        self.class.trace_execution_scoped metrics do
          run_request_without_newrelic_trace(method, url, params, headers, &block)
        end
```

If we were to add auto-instrumentation for Faraday, we'd have to think of what Faraday is providing over and above the adapters it's capable of using that we also not already instrumenting.  As it is right now, since we auto-instrument many of the adapters Faraday can work with (Net::HTTP, Excon, HTTPClient, etc.), I'm wondering what that extra overhead and meta data we could collect that would be useful in the APM UI to see.  It may be _more_ useful to add auto-instrumentation for the various adapters mentioned by Faraday instead of instrumenting Faraday directly.

**Comment by angelatan2** [comment]
@waissbluth Based on the response that @mwlang provided, we, at this time do not see the advantage of instrumenting Faraday over the current adapters approach. We decided that we won't be adding this feature in the near future. If there is more new information regarding this request, please do not hesitate to reopen the ticket.
