### ISSUE TITLE
 ERROR : NameError: undefined local variable or method `headers' for NewRelic::Agent::DistributedTracing:Module

### ISSUE THREAD

**Issue by kjkuan** [newrelic/newrelic-ruby-agent#616]
## Description
We keep seeing this error message in our logs from NewRelic:
```
** [NewRelic][2021-03-11 14:33:40 +0000 sidekiq_worker.14.7909 (1)] ERROR : error during accept_distributed_trace_headers
** [NewRelic][2021-03-11 14:33:40 +0000 sidekiq_worker.14.7909 (1)] ERROR : NameError: undefined local variable or method `headers' for NewRelic::Agent::DistributedTracing:Module
```

## Expected Behavior
No such error messages.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 

## Your Environment
- ruby `2.5.7`
- rails `6.0.3.5`
- newrelic_rpm gem `6.12.0.367` or `6.15.0`

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

**Comment by tannalynn** [comment]
Hello @kjkuan
Thank you for bringing this to our attention.

This appears to be related to distributed tracing in your sidekiq worker, based on what i'm reading in that log message.
So, our [sidekiq instrumentation](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/sidekiq.rb#L34), specifically the server instrumentation, calls that [api method](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/distributed_tracing.rb#L165) mentioned in the log message. I'm honestly scratching my head a bit about that error because `headers` is an argument that is passed into this method, it shouldn't be confused about where that's coming from.

I have a couple of follow up questions to try and get a better picture of what's going on here. 
- You mention you see them often, does it appear to be every time, or a frequent intermittent issue?
- Are you seeing missing data from your sidekiq workers (or server maybe) in the distributed tracing view?
- Distributed tracing for sidekiq was release in 6.11, is it possible your application had custom instrumentation for sidekiq before this change was introduced? Or perhaps a 3rd party newrelic gem for sidekiq? If either of those is the case, perhaps there is some conflict between that and the current instrumentation.

**Comment by dalizard** [comment]
@kjkuan @angelatan2 The problem was already [fixed](https://github.com/newrelic/newrelic-ruby-agent/pull/558), I think we are simply waiting on official release 😃

**Comment by kjkuan** [comment]
Thanks! will upgrade once the new version is out.
