### ISSUE TITLE
Distributed tracing raise TypeError

### ISSUE THREAD

**Issue by deskcoder** [newrelic/newrelic-ruby-agent#647]
## Description

When I'm trying to enable distributed tracing

```
  distributed_tracing:
    enabled: true
```

and sending a request to `grape` endpoint newrelic_rpm is raising 

```
[2021-04-13 13:47:55 +0200 Pawels-MBP (50219)] WARN : TypeError: no implicit conversion of nil into String
[2021-04-13 13:47:56 +0200 Pawels-MBP (50219)] WARN : Failed to create trace context payload
```

Disabling distributed tracing makes the error disappear

## Expected Behavior

distributed_tracing should not cause TypeError.

## Troubleshooting

I tried to debug newrelic_rpm and I found that it's failing here

https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/distributed_tracing/trace_context_payload.rb#L115

```
[1] pry(#<NewRelic::Agent::TraceContextPayload>)> parent_type_id
=> 0
[2] pry(#<NewRelic::Agent::TraceContextPayload>)> parent_account_id
=> nil
[3] pry(#<NewRelic::Agent::TraceContextPayload>)> parent_app_id
=> nil
[4] pry(#<NewRelic::Agent::TraceContextPayload>)> (id || NewRelic::EMPTY_STR)
=> "3da91fe34363e02d"
[5] pry(#<NewRelic::Agent::TraceContextPayload>)> (transaction_id || NewRelic::EMPTY_STR)
=> "c222ba904bcb934f"
[6] pry(#<NewRelic::Agent::TraceContextPayload>)> (sampled ? TRUE_CHAR : FALSE_CHAR)
=> "1"
[7] pry(#<NewRelic::Agent::TraceContextPayload>)> sprintf("%.6f", priority)
=> "1.405902"
[8] pry(#<NewRelic::Agent::TraceContextPayload>)> timestamp.to_s
=> "1618315522770"
```

basically for whatever reason, `parent_account_id` is `nil`  so this line fails with

```
[10] pry(#<NewRelic::Agent::TraceContextPayload>)> result << DELIMITER << parent_account_id
TypeError: no implicit conversion of nil into String
```

I'm not sure about newrelic internals but I'm guessing the real issue is somewhere else and this is just a side effect of it. Maybe some gems I'm using are outdated and not supported by newrelic anymore?

## Steps to Reproduce

It's a company application but I think I could give you private access to check it yourself.

## Your Environment

Gemfile.lock: https://gist.github.com/deskcoder/6ce507cb58c8bfb3392a81d55b671e48
newrelic_agent.log: https://gist.github.com/deskcoder/ef72112ac555064f707b2f9d4713f5a3
ruby: 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

newrelic account: 3137787
newrelic application: 178347404

**Comment by tannalynn** [comment]
Hello, @deskcoder 
Thank you for bringing this to our attention. Just to confirm, this error only happens near the beginning of the start up for the application, correct?

So, the `parent_account_id` is a value the agent receives in the response when first connecting to the new relic servers. The agent is supposed to wait to do anything until we receive that first response from the new relic servers, since it sends back data the agent needs, including things like server side configs, agent run token, etc. So basically what's happening here here is that the agent is trying to record this distributed tracing data before the agent is supposed to.

This doesn't lead to any data loss at least, since I believe the correct behavior for the agent is to simply not record data before the agent finishes startup. Once the agent does receive that response from the servers, this error will not happen the next time it tries to create a trace context payload. 

So this does appear to be a bug in the agent, but it shouldn't be impacting the application, does that seem to match what you are experiencing? Are you able to see any data reporting on the UI?
