### ISSUE TITLE
Stack level too deep issue

### ISSUE THREAD

**Issue by denisahearn** [newrelic/newrelic-ruby-agent#656]
## Description
I upgraded my Rails app today to use version 7.0.0 of this gem, and now I'm seeing the following error in the passenger log when the Rails app starts up:

```
App 16680 stderr: #<Thread:0x000055b2c499a9b8@/data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/threading/agent_thread.rb:12 run> terminated with exception (report_on_exception is true):
App 16680 stderr: /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `initialize_dup': stack level too deep (SystemStackError)
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `dup'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `unencode'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:1401:in `port='
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:831:in `block in initialize'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:2392:in `defer_validation'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:823:in `initialize'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:138:in `new'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:138:in `parse'
App 16680 stderr: 	 ... 10638 levels...
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/agent.rb:677:in `catch_errors'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/agent.rb:696:in `deferred_work!'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/agent.rb:723:in `block in start_worker_thread'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/threading/agent_thread.rb:14:in `block in create'
App 16680 stderr: #<Thread:0x000055b2c4999f18@/data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/threading/agent_thread.rb:12 run> terminated with exception (report_on_exception is true):
App 16680 stderr: /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `initialize_dup': stack level too deep (SystemStackError)
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `dup'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `unencode'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:1401:in `port='
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:831:in `block in initialize'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:2392:in `defer_validation'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:823:in `initialize'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:138:in `new'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:138:in `parse'
App 16680 stderr: 	 ... 10638 levels...
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/agent.rb:677:in `catch_errors'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/agent.rb:696:in `deferred_work!'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/agent.rb:723:in `block in start_worker_thread'
App 16680 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/threading/agent_thread.rb:14:in `block in create'
```
I read the documentation at https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/migration-7x-guide/#prepend-instrumentation, and then tried adding the following setting to my newrelic.yml file to resolve the issue:

```
instrumentation:
  addressable: chain
```

but that did not resolve the error. 

I then tried this:

```
instrumentation:
  addressable: disable
```

but that also did not resolve the error.

I assume from the stack trace that the issue is with the addressable gem, however perhaps that's not the case. It wasn't super clear to me from the documentation how to identify the exact gem that is causing the issue.

I have attached my full `config/newrelic.yml` file below (zipped so that GitHub would accept it):

[newrelic.yml.zip](https://github.com/newrelic/newrelic-ruby-agent/files/6380293/newrelic.yml.zip)

## Expected Behavior
I was expecting the "Stack level too deep" issue to be solved by configuring the addressable to use method-chaining.

## Steps to Reproduce
I see the "Stack level too deep" error in the passenger log when the Rails app starts up. Once it's running, and it handling web requests, I don't see further occurrences of this error (until the next time the passenger processes start up again).

## Your Environment
Rails 6.1.3.1
Ruby 2.6.6
Passenger 5.1.8

**Comment by tannalynn** [comment]
Hello @denisahearn 
The agent doesn't instrument the addressable gem, which is why you saw no change adding it to your newrelic.yml. However, it does appear that there is a conflict with prepend in one of the gems we are instrumenting. Since that stack trace isn't the full stack trace, it's a bit hard to tell which gem that we are instrumenting is part of the conflict.  
However, I suspect it's likely the http library you are using. The first one I would suggest trying to set to chain is Net::HTTP, since it is the most common. So try adding 
```
instrumentation:
  net_http: chain
```
to your newrelic.yml. 
If that doesn't resolve the issue for you, others you could try setting to chain (depending on what you are using in your application) are:
```
typhoeus
httpclient
httprb
curb
rack
rack_urlmap
```

**Comment by denisahearn** [comment]
Hi @ tannalynn

Thanks for responding. I tried `net_http: chain` but I am still seeing the issue when my Rails app starts up.
Below is the Passenger log file with the full output. Can you please take a look and see which gem is having the problem. I try looking at the output and it's not clear to me which gem is the culprit.

[passenger.8000.log.zip](https://github.com/newrelic/newrelic-ruby-agent/files/6380904/passenger.8000.log.zip)

Denis

**Comment by tannalynn** [comment]
@denisahearn is this latest log that you included using 
```
instrumentation:
  net_http: chain
```
 I ask because in many of the stack traces I'm seeing this
```
App 25199 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:14:in `request_with_tracing'
App 25199 stderr: 	from /data/cloudvault/shared/bundled_gems/ruby/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:16:in `request_with_newrelic_trace'
```
which to me looks like it could be pointing towards a conflict with the agent using chain for net_http and something else using prepend. However, since the stack trace is cut off, it's hard to tell if this is the problematic part of the stack trace, or something happening before that. 

Also, I'm still unable to see the full stack traces since the middle of them is cut out and replaced with the line that says
```
App 25199 stderr: 	 ... 10638 levels...
```
So that's why it's hard to tell which of our instrumentation may be involved. If you are able to somehow have it output the full stack trace (even though it'll be super long), that would likely be helpful in narrowing it down. It's usually easier to tell where the conflict is coming from when looking at the stack trace, but I suspect the important parts to us are being cut out.
Perhaps the rack instrumentation might be implicated. I haven't seen any conflicts yet with rack, but I wouldn't be surprised if the rack lines are just more in the middle of the stack trace and being cut out.

**Comment by denisahearn** [comment]
Hi @tannalynn

I was able to duplicate the problem in my local Rails development environment, and was also able to capture the full stack trace, which is attached below.

[development.log.zip](https://github.com/newrelic/newrelic-ruby-agent/files/6385163/development.log.zip)

Denis

**Comment by tannalynn** [comment]
@denisahearn Looking at that stack trace in particular, it looks like the net_http instrumentation being set to chain is part of the problem for this one in particular, with airbrake being what is conflicting. 
```
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:16:in `block in request_with_newrelic_trace'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:26:in `block (2 levels) in request_with_tracing'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/tracer.rb:371:in `capture_segment_error'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:25:in `block in request_with_tracing'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/newrelic_rpm-7.0.0/lib/new_relic/agent.rb:501:in `disable_all_tracing'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:24:in `request_with_tracing'
/Users/denisahearn/.rvm/gems/ruby-2.6.5@cloudvault/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:16:in `request_with_newrelic_trace'
```
You can see here, where the stack trace points to, https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/net_http.rb
that they are using prepend here. I'd recommend changing the config to use prepend explicitly
```
instrumentation:
  net_http: prepend
```

Previously, we actually added a [conflicts_with_prepend](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/net_http.rb#L20) for airbrake due to a conflict being reported, however going back, it looks like newer versions of airbrake are no longer using monkey patching, which is something we missed when adding this check.

We added these conflicts_with_prepend in order to try to make things easier for our customers when using auto instrumentation, however it seems that in this case it is not being help out. I'm going to recommend we remove this conflict so that users with newer version of airbrake don't run into this issue again.

When using auto (the default) for these values, we check to make sure there isn't a known conflict before using prepend, however, the agent should use prepend anyways if you explicitly state it in the newrelic.yml like above. 

If you see continue to see an error after explicitly setting it to prepend, I'd recommend checking the newrelic_agent.log to confirm that you see a line that says
```
INFO : Installing New Relic supported NetHTTP instrumentation using Prepend
```
If that says "chain" instead, please let me know, as that should not be the case if you are explicitly setting it to prepend in your config.

Additionally, you could try setting it to be disable and try running again. If you continue to see an error after that, it's possible there is also another conflict, so the stack trace at that point could help narrow it down for that second conflict. However, at this point I suspect that the issue is most likely net_http and our conflict_with_prepend check.

**Comment by denisahearn** [comment]
Hi @tannalynn

Added `net_http: prepend` appears to have fixed the "Stack level too deep" issue that I was seeing in the Passenger log file. Passenger is now able to start up the Rails app cleanly. 

However, I'm now seeing a similar "Stack level too deep" error raised by our Resque workers when they run a background job (we send information from our background jobs to NewRelic). Attached is the stack trace for this:

[resque-worker-stacktrace.txt.zip](https://github.com/newrelic/newrelic-ruby-agent/files/6386724/resque-worker-stacktrace.txt.zip)

Any thoughts on what needs to be done to work around this issue?

Thanks,
Denis

**Comment by tannalynn** [comment]
@denisahearn That's great that the net_http related errors are gone after setting it to prepend.

For resque, it looks like airbrake is using method chaining for resque still, even though they have updated net_http to prepend.
The stack trace shows the infinite loop is stuck on perform for resque between the agent and airbrake (since it's repeating over and over)
```
/GEM_ROOT/gems/airbrake-11.0.1/lib/airbrake/resque.rb:44 in block in perform
/GEM_ROOT/gems/airbrake-ruby-5.2.0/lib/airbrake-ruby/benchmark.rb:13 in measure
/GEM_ROOT/gems/airbrake-11.0.1/lib/airbrake/resque.rb:43 in perform
/GEM_ROOT/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/resque/prepend.rb:12 in block in perform
/GEM_ROOT/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/resque/instrumentation.rb:22 in block in with_tracing
/GEM_ROOT/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376 in perform_action_with_newrelic_trace
/GEM_ROOT/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/resque/instrumentation.rb:12 in with_tracing
/GEM_ROOT/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/resque/prepend.rb:12 in perform
```
Looking at their code, https://github.com/airbrake/airbrake/blob/master/lib/airbrake/resque.rb, you can see they are still using method chaining, so setting resque instrumentation to chain in your newrelic.yml should solve this issue.
```
instrumentation:
  resque: chain
```

**Comment by denisahearn** [comment]
@tannalynn - Just to follow up on this, adding `resque: chain` to our NewRelic configuration fixed the issue we were seeing with our Resque jobs. 

We are still QAing our gems upgrade (which includes the upgrade to newrelic_rpm 7.0.0), but as of right now we're not seeing any more issues caused by the NewRelic gem than the ones I've already reported.

Thanks again for your help with this.

Denis

**Comment by tannalynn** [comment]
@denisahearn That's great to hear! Glad we could help get things working. 
We've added/updated these conflicts you reported to our auto-detection, so in future agent versions the agent will avoid using prepend when there one of these known conflicts is detected.
