### ISSUE TITLE
Offer a sample config file with every option

### ISSUE THREAD

**Issue by sdhull** [newrelic/newrelic-ruby-agent#684]
### Is your feature request related to a problem? Please describe.
Trying to get a `newrelic.yml` file going and it's extremely frustrating that there is no way to generate one (or copy a template or... something). Please take [the devise config file](https://github.com/heartcombo/devise/blob/master/lib/generators/templates/devise.rb) as an example of a library doing "The Right Thing." There are a ton of comments in there and nearly every available option is in there, but commented out so it's easy to go in and uncomment lines you want to customize, rather than go hunt through the docs and painstakingly copy over the correct keys.

### Feature Description
How about a simple `rake newrelic:config:generate` or `newrelic config generate` if the gem has an executable. Basically a simple way to generate a config file with every possible key in it.

### Describe Alternatives
Alternatively you could offer a `newrelic.yml` example file in the repo or in the docs themselves. There's also a "download fresh config" thing available in `Account Settings`, you could update that so it would generate a fully-fleshed-out config file (right now it's v anemic).

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Nice to Have

**Comment by tannalynn** [comment]
Thank you for bringing up this suggestion. That makes sense that that would be a helpful tool for customers to have a config file to start with that has all the options the the agent supports. I'll discuss it with my team about how to prioritize this request.

**Comment by elucus** [comment]
We will look to address this when we start work on improving the deployment experience.

**Comment by wyhaines** [comment]
Just FYI, but I picked this up on the new_relic Twitch stream yesterday.

There is a way to generate a config file (`newrelic install...`), but the config file is pretty sparse. It is documented here:

https://docs.newrelic.com/docs/agents/ruby-agent/installation/install-new-relic-ruby-agent/

But maybe in the README it could be mentioned, as well?

In any event, the plan is to just iterate through all of the config options, and insert them into the template with basic explanations of what they can do, and the default values for them, but having all of them commented out.

This is the pattern used by devise, as referred to by the OP, as well as numerous other packages.

If you have any specific thoughts or suggestions about the direction to take this, let me know. Otherwise, I'll work through it the way that I am going, and then submit a PR for you to review.

**Comment by elucus** [comment]
Hi @wyhaines, I think having a config template with explanations is a good idea and we'd be happy to have your help.

**Comment by creaturenex** [comment]
Added relevant config options to the file except for deprecated options. Waiting for @wyhaines to review and submit PR.

**Comment by wyhaines** [comment]
💪 Thanks @creaturenex !  I will be reviewing it later today, or maybe very very early US time tomorrow (I am in UTC-1 right now).

**Comment by tannalynn** [comment]
PR merged
