### ISSUE TITLE
Jbuilder method tracer exception in v8.0.0

### ISSUE THREAD

**Issue by toncid** [newrelic/newrelic-ruby-agent#789]
## Description
After a gem upgrade from v7.2.0 to v8.0.0, an exception is raised by the `Jbuilder#target!` method tracer.

## Expected Behavior
To continue working as it did before the upgrade.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.

```
[ActionView::Template::Error] undefined method `trace_execution_scoped' for nil:NilClass | Stack trace:
	/Users/tonci/.rvm/gems/ruby-2.6.7/gems/newrelic_rpm-8.0.0/lib/new_relic/agent/method_tracer.rb:326:in `block (2 levels) in _nr_define_traced_method'
	/Users/tonci/.rvm/gems/ruby-2.6.7/gems/jbuilder-2.11.2/lib/jbuilder/jbuilder_template.rb:81:in `target!'
	/Users/tonci/Documents/server/app/views/api/v1/authentication/login.json.jbuilder:8:in `_app_views_api_v__authentication_login_json_jbuilder___2930598681177930957_70166338224360'
	... 
```

## Steps to Reproduce
We add a method tracer to measure actual JSON serialization performance of `Jbuilder`:

```ruby
class Jbuilder
  include ::NewRelic::Agent::MethodTracer

  add_method_tracer :target!, 'View/Jbuilder/target!'
end
```

This code is executed as a Rails initializer in `config/initializers/newrelic.rb`.

Afterwards, just call the `target!` method:

```ruby
Jbuilder.new.target!
```

## Your Environment
Ruby v2.6.7, Rails v5.2.6, both macOS and Linux affected.

## Additional context
Nothing right now.

**Comment by angelatan2** [comment]
@toncid, thank you for updating and reporting this issue regarding our new release.  We will have someone take a look.

**Comment by amhuntsman** [comment]
Hello @toncid! I'm looking at our agent code and at Jbuilder, and I think I've found the root of the problem. `Jbuilder` is actually a proxy class that does not include `Kernel` by default. The Ruby Agent 8.0.0 update changes method tracers to require `self.class` for inspection when running traced methods; because `Kernel#class` is not defined, you get the error above.

While we work on a fix, I would suggest this possible workaround in your initializer:

```ruby
class Jbuilder
  include ::Kernel
  include ::NewRelic::Agent::MethodTracer

  add_method_tracer :target!, 'View/Jbuilder/target!'
end
```

**Comment by toncid** [comment]
Hello @amhuntsman,

Thank you for your analysis. Unfortunately, this is probably not a good solution.

The reason for this is Jbuilder's flexibility to create JSON based on `method_missing` calls, meaning that `Kernel` methods would be called instead and therefore cause side-effects, should they be included as you proposed.

For example, if you wanted a `warn` field in JSON, it would be added like this:

```ruby
json = Jbuilder.new
json.warn true
json.target!  # yields: {"warn":true}
```

However, including the `Kernel` module would print `true` to `$stderr` and yield and we would end up with an empty object `{}` in the end.

Hope this makes sense.

**Comment by amhuntsman** [comment]
@toncid That does make sense, and thank you for the clarification. For the time being, unfortunately, Ruby Agent 8.0.0 does not support using `add_method_tracer` on proxy objects such as Jbuilder. This will be addressed and fixed in an upcoming release.

That said, one other possible workaround is to patch `target!` in the initializer to use a lower-level tracing method:
```
class Jbuilder
  def target!
    ::NewRelic::Agent::MethodTracer.trace_execution_scoped(['View/Jbuilder/target!']) do
      @attributes.to_json
    end
  end
end
```

From an agent development standpoint, we're also curious about the use case for tracing the `target!` method. My in-depth knowledge of Jbuilder is limited, but `target!` seems only to run `@attributes.to_json`. Based on a quick glance at `JbuilderTemplate` other JSON rendering solutions in the wild, could the bulk of processing overhead be in the template logic rather than in `target!`?

**Comment by toncid** [comment]
@amhuntsman Thank you for the reply.

> That said, one other possible workaround is to patch `target!` in the initializer to use a lower-level tracing method:

This can also work for us, at least until the patch is released. Thanks!

> From an agent development standpoint, we're also curious about the use case for tracing the `target!` method. My in-depth knowledge of Jbuilder is limited, but `target!` seems only to run `@attributes.to_json`. Based on a quick glance at `JbuilderTemplate` other JSON rendering solutions in the wild, could the bulk of processing overhead be in the template logic rather than in `target!`?

You are right - with Jbuilder, the bulk of processing is in the template logic, but in order to know how much time is actually spent in it, we have to eliminate JSON encoding that converts the final Ruby object to its JSON representation (usually handled by the `json` or `oj` gem). Hope this clarifies.
