### ISSUE TITLE
Update Core Tech: Sidekiq Gem

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#793]
- [ ] Understand if methods were deprecated by gem owners.
- [ ] Find new methods that are of value (useful to our customers)
- [ ] Instrument those new methods
- [ ] Update our multiverse to dynamically pull the latest version so that we do not have to manually update each gem version number manually.

**Comment by kaylareopelle** [comment]
Relates to #1479

**Comment by kaylareopelle** [comment]
Relates to #1567

**Comment by daskycodes** [comment]
Since `Sidekiq::Extensions::DelayedClass` has been removed from Sidekiq 7.0 and put into a separate Gem, this would also need to be added to the newrelic ruby agent:

https://github.com/gemhome/sidekiq-delay_extensions

**Comment by kaylareopelle** [comment]
Thank you, @daskycodes!

**Comment by tannalynn** [comment]
The embedded feature described in the [7.0 upgrade guide](https://github.com/mperham/sidekiq/blob/main/docs/7.0-Upgrade.md#embedding) appears to be working well with the agent from what I've tested. All the expected data is showing up and everything looks the same as when it is not used. It doesn't look like there is anything additional that would need to be recorded for it either, since it's basically just running the server inside the main application rather than a different process. 

Sidekiq metrics is info is discussed here https://github.com/newrelic/newrelic-ruby-agent/issues/1479

I didn't get a chance to look into the capsules or redis related items mentioned in the [upgrade guide](https://github.com/mperham/sidekiq/blob/main/docs/7.0-Upgrade.md).

**Comment by kaylareopelle** [comment]
@tannalynn  - Thanks for looking into this! From your analysis, it seems like we don't have any action to take to update Sidekiq instrumentation this time around. Is this issue safe to close out? Or would you prefer we look into capsules and Redis-related items first?

**Comment by tannalynn** [comment]
> Thanks for looking into this! From your analysis, it seems like we don't have any action to take to update Sidekiq instrumentation this time around. Is this issue safe to close out? Or would you prefer we look into capsules and Redis-related items first?

It doesn't seem like there is anything with those that would make sense for us to instrument really, even though I didn't have a chance to really dig into them. I think at this point it makes sense to close it out.
