### ISSUE TITLE
Update Core Tech: Excon Gem

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#794]
This is a follow-up story from Ignite Sprint's goal.
- [x] Understand if methods were deprecated by gem owners.
None of the currently instrumented methods, [request_call](https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L112), [response_call](https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L206), or [error_call](https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L106), have been deprecated. 
- [x]  Find new methods that are of value
There have been no new introduced methods of value—and hardly any new methods at that! Excon does version updates frequently, however most releases only include small refactors and certificate updates. They appear to follow semver versioning and are still on major version 0, pointing to no major updates to consider. [CHANGELOG](https://github.com/excon/excon/blob/master/changelog.txt)
- [x] Instrument those new methods
NA
- [x] Update our multiverse to dynamically pull the latest version so that we do not have to manually update each gem version number manually.
We are currently always pulling in the latest version and all tests are passing. We appear to be unnecessarily testing different versions, so a follow-up PR will be created to remove these and reduce testing overhead.

**Comment by hannahramadan** [comment]
- [x] Understand if methods were deprecated by gem owners.
None of the currently instrumented methods, [request_call](https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L112), [response_call](https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L206), or [error_call](https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L106), have been deprecated. 

- [x]  Find new methods that are of value
There have been no new introduced methods of value—and hardly any new methods at that! Excon does version updates frequently, however most releases only include small refactors and certificate updates. They appear to follow semver versioning and are still on major version 0, pointing to no major updates to consider. [CHANGELOG](https://github.com/excon/excon/blob/master/changelog.txt)

- [x] Instrument those new methods
NA

- [x] Update our multiverse to dynamically pull the latest version so that we do not have to manually update each gem version number manually.
We are currently always pulling in the latest version and all tests are passing. We appear to be uncessarily testing different versions, so a followup PR will be created to remove these and reduce testing overhead.

**Comment by kaylareopelle** [comment]
@hannahramadan  - Are we all clear to close out this issue?

**Comment by kaylareopelle** [comment]
Chatted with Hannah and we're good to close! 😎
