### ISSUE TITLE
missing transaction in transactions list

### ISSUE THREAD

**Issue by gsar** [newrelic/newrelic-ruby-agent#804]
## Description

We have a high throughput controller endpoint that is completely missing in the transactions list. It does show up occasionally in the slow transactions list, and when clicked on, the graphs for `App Performance` and `Throughput` look like this (showing 0 ms, 0 rpm):

![image](https://user-images.githubusercontent.com/6981812/135774401-c7f6b65d-23a7-474b-b01a-d6fb81857800.png)

## Expected Behavior

Transaction should appear in the transactions list--in fact it is one of the endpoints that is called with high frequency by the app.

## Steps to Reproduce

Unsure how to reproduce.

The only difference from other controller methods in the same controller that do appear in the transactions list is that the missing `counts` method is mentioned in a `prepend_before_action :skip_trackable, only: [:counts]` in the controller. `skip_trackable` is defined to do this:

``` ruby
  def skip_trackable
    request.env['devise.skip_trackable'] = true
  end
```

## Your Environment

NewRelic Ruby Agent 7.2.0
Rails 6.1.4.1
Ruby 3.0.2

**Comment by kaylareopelle** [comment]
Hi @gsar, thanks for reaching out! 

After assessing the issue, [New Relic Support](https://github.com/newrelic/newrelic-ruby-agent#support) seems best positioned to assist with this specific issue. You can engage the New Relic Support Community or open a support ticket, depending on your support level.  Please provide a link to this GitHub issue when submitting your community post or support ticket.

**Comment by kaylareopelle** [comment]
I want to clarify the reasoning behind my message earlier this week. I noticed I just said the word “assess” without further background. Here it is:

At this time, it’s hard to tell whether this is a bug within the agent or another service (such as a UI component or NRDB). Our support team is versed in each of these layers and will cross-reference your issue with other similar reports to narrow down the root cause. If the support team deems it is an agent-related issue, it will pop back into our laps and we’ll re-assess then.

We really appreciate your active support and reporting on this codebase. I hope my terse redirection didn’t deter your enthusiasm. We’re very grateful for your contributions.
