### ISSUE TITLE
NoMethodError: undefined method `<' for nil:NilClass leads to "Failure when capturing error 'READONLY You can't write against a read only slave.':"

### ISSUE THREAD

**Issue by olleolleolle** [newrelic/newrelic-ruby-agent#817]
## Description

👋 I was investigating a report in our Honeybadger exception catcher, which we are using in conjunction with NewRelic.

In the stack of warnings and exception backtrace, I could see that NewRelic Ruby client had tried to capture the exception, but emitted an error:

    Failure when capturing error 'READONLY You can't write against a read only ...':

This "Failure when capturing" message comes from newrelic_rpm. That's `exception` in this line: https://github.com/newrelic/newrelic-ruby-agent/blob/24bf088f4fb2536cb0753b72960bbe5b5a420031/lib/new_relic/agent/error_collector.rb#L246

Now, just next to that was _WARN_ message, and this is the `e` in the code above

    NoMethodError: undefined method `<' for nil:NilClass

<img width="988" alt="bild" src="https://user-images.githubusercontent.com/211/138277916-ca38e409-749a-4380-a6fd-7c8a2605b916.png">

Could it be that the code which is capturing runs into some trouble?

The `Redis::CommandError` exception being managed is derived from RuntimeError, nothing special about it:
 https://github.com/redis/redis-rb/blob/6542934f01b9c390ee450bd372209a04bc3a239b/lib/redis/errors.rb#L20

## Expected Behavior

I expect no specific messages to be emitted.

## Steps to Reproduce

- Have a Redis READONLY instance
- Stack both newrelic_rpm and honeybadger-ruby to do exception notifications
- Try connecting to Redis using the redis-4.5.1 gem

## Your Environment

- `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]`
- this gem: 8.0.0

**Comment by angelatan2** [comment]
@olleolleolle Thank you for submitting an issue and calling our attention to this problem.  We appreciate it.  Our developers will review this ticket soon.

**Comment by tannalynn** [comment]
Hello @olleolleolle 
I was curious if you see this same NoMethodError when using new relic without honeybadger? 
I'm wondering if it's possible this issue is happening due to some interaction between those two gems, or if this still occurs when just new relic is being used. That will help me narrow down what to look at next in our investigation on this. 
Thank you!

**Comment by olleolleolle** [comment]
Apologies, I don't have anything else to go on, I went and looked. This is all I have.

**Comment by kaylareopelle** [comment]
Hi @olleolleolle, we appreciate you trying to gather more information. We'll take a closer look and try to narrow down the issue.

**Comment by tannalynn** [comment]
Hello @olleolleolle!
I took a stab at this issue again recently since it had been a while since we last spent time on this issue. We weren’t able to reproduce it previously so we didn't know what was causing the issue, but this time we were actually eventually able to reproduce the same ` NoMethodError: undefined method `<' for nil:NilClass` error and track it down. 
It turns out this error is actually not related to redis or sidekiq, but appears to actually be a bug in how we are creating error events when notice_error is called outside the scope of a transaction.  

I’ve created a PR to resolve this issue https://github.com/newrelic/newrelic-ruby-agent/pull/1128
Thanks for reporting this bug! Took us a while to figure out what was going on but this should be resolved when this bug fix is released.
