### ISSUE TITLE
Remove newrelic/rpm from RubyDoc.info

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#826]
It seems like there is a connection to our outdated, private repository on RubyDoc.info under the name `newrelic/rpm`:
https://rubydoc.info/github/newrelic/rpm 

Let's find a way to either:
A. Take this down
B. Sync it with our maintained repo

The goal is to prevent outdated documentation from being available for our agent.

**Comment by pizzaz93** [comment]
This is what I see on the linked page:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/10904763/164816870-c5876cd4-812b-4f2a-ae11-1f37735a0fd4.png"> 

When I entered `https://github.com/newrelic/rpm`  in the search box I was redirected to the generated docs at [https://rubydoc.info/github/newrelic/rpm/dev](https://rubydoc.info/github/newrelic/rpm/dev)

**Comment by tannalynn** [comment]
We renamed our repository a year and a half ago (ish), so that might be related. Also, weirdly, when I go to the link in the original post, it doesn't give me that same Oops page you're seeing @pizzaz93. Not sure why.
Not sure if it'll be related, but I think something changed recently with rubydocs because a lot of the links we've been using stopped working suddenly sometime in the last week or 2. We're updating our docs site as well because our links to rubydocs don't work anymore, so we're updating to to use https://rubydoc.info/gems/newrelic_rpm instead.
