### ISSUE TITLE
Assess the changes and new content in Rails 7.0

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-ruby-agent#875]
Review the release notes for:

https://edgeguides.rubyonrails.org/7_0_release_notes.html

1. Identify the impact of removed methods 

- Methods that were removed, was it because the feature was removed, or was it because there are new methods/libraries introduced to cover the functionality.
- If new methods/libraries were introduced to cover the functionality,  does our current instrumentation support the new methods/libraries?  If no, please create an issue for future instrumentation.

2. Identify the impact of deprecated methods

- Provide high-level impact of these deprecated methods.

**Comment by kaylareopelle** [comment]
See [MMF: Rails 7.0 Support](https://docs.google.com/document/d/1NABn3IGIdbILTMaYXhjnaBbq4ZH8sD6vVjdxS-tSCE8/edit#) for details about the new features we're investigating.

Our team is researching changes to instrument:
* Asynchronous Query Loading 
* At-Work Encryption With ActiveRecord
* ActionController::Live#send_stream
* Active Storage now uses libvips instead of ImageMagick
* Trace Query Origins with Marginalia-Style Tagging as ActiveRecord QueryLogs
* tag.attributes - Translates a hash to HTML attributes

Major Javascript changes introduced in Rails 7.0 do not fall within the purview of the Ruby Agent.
