### ISSUE TITLE
expected_status_codes is not marking errors as expected

### ISSUE THREAD

**Issue by aelmekeev** [newrelic/newrelic-ruby-agent#929]
## Description
I'm trying to ignore some transaction errors that we have with the help of [`error_collector.expected_status_code`](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#error_collector-expected_status_codes). But they are still not marked as expected in New Relic.

## Expected Behavior
With below config I would expect all TransactionError with `http.statusCode` as `409` to be marked as expected.
```
error_collector.expected_status_codes: "409"
```
`error_collector.ignore_status_codes` is working fine.
`error_collector.expected_classes` though is working fine but I cannot set it up through environment variable.

Here the first transaction is from the app where `ignore_status_codes` is configured to `409`. Second one with `expected_status_codes`. And the third one with `expected_classes`.
![image](https://user-images.githubusercontent.com/55494848/151382024-01d9135b-0cf6-4979-9c72-30e834a2cb68.png)

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

Would like to avoid posting logs since I'm not sure how to properly clean them up.

## Steps to Reproduce
Configure `error_collector.expected_status_codes` with any error code and trigger an error in the app with this code.
Check TransactionError table to confirm that `error.expected` is not `true`.

## Your Environment
Verified with ruby agent `7.2.0` and `8.4.0`.
Ruby: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]`.

## Additional context
Original feature: https://github.com/newrelic/newrelic-ruby-agent/issues/455

**Comment by kaylareopelle** [comment]
Hi @aelmekeev! Thanks for bringing this to our attention. I've been able to reproduce this bug locally and am looking into a solution.

I do think that logs, your `newrelic.yml` file, and `Gemfile` would all be helpful in getting to the root cause. These files can be securely shared through the [New Relic Support](https://github.com/newrelic/newrelic-ruby-agent#support) portal.

You can engage the [New Relic Support Community](https://discuss.newrelic.com/) or open a [support ticket](https://support.newrelic.com/new-ticket), depending on your support level.  Please provide a link to this GitHub issue when submitting your community post or support ticket and we'll reconnect on that forum!

**Comment by kaylareopelle** [comment]
Hi @aelmekeev! Did you happen to file a ticket with support? I wanted to check in because we haven't seen anything on the dashboard yet!

**Comment by aelmekeev** [comment]
Hi @kaylareopelle sorry I somehow missed your reply.
Unfortunately, we no longer use New Relic and hence I'm not that interested in this fix.
