### ISSUE TITLE
Fix intermittent active_record_pg error on Ruby 3.0.3

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#969]
An intermittent failure has popped up within the new `active_record_pg` suite on Ruby 3.0.3. Full output below. Sometimes it passes with the expected call count of 5, other times it returns 6 (as it does below) or 8.

```
1) Failure:
ActiveRecordInstrumentationTest#test_metrics_for_calculation_methods [/home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/test/multiverse/suites/active_record_pg/active_record_test.rb:53]:
Expected call_count for Datastore/statement/Postgres/Order/select to be 5, got 6.
Actual stats:
  Call count:           6
  Total call time:      0.003542661666870117
  Total exclusive time: 0.003542661666870117
  Min call time:        0.0003266334533691406
  Max call time:        0.0016031265258789062
  Sum of squares:       3.3352982313772372e-06
  Apdex S:              6
  Apdex T:              0.003542661666870117
  Apdex F:              0.003542661666870117
.
Expected: 5
  Actual: 6

45 runs, 52 assertions, 1 failures, 0 errors, 0 skips
No tests found with those options.
options: []
"active_record_pg" for Envfile entry 0 failed!
```

**Comment by fallwith** [comment]
Findings:

* There is a single failing Minitest test is involved, which is `test_metrics_for_calculation_methods` defined in `test/multiverse/suites/active_record_pg/active_record_test.rb`
* The problem will only occur when Rails versions < 7 are tested, given that `test_metrics_for_calculation_methods` only layers in a count with the assertion if ActiveRecord is below version 7.0
* The failing test is only attempted against Postgres, but a very similar test of the same name defined by `test/multiverse/suites/active_record/active_record_test.rb` tests MySQL in conjunction with ActiveRecord v3+ and performs the same assertion of expecting there to be 5 `SELECT` statements, so this appears to be a Postgres only issue.
* From examining the extra recorded `SELECT` statements that cause the test to fail, they all take place before the test's own database activity and they all appear to be related to Postgres' schema cache and TypeMap.
* The sometimes unexpected nature of these extra queries firing is an ongoing issue of discussion within the Rails community. See [Rails PR 44478](https://github.com/rails/rails/pull/44478) for example.

Now that we have identified the root cause of the test failures, we have two different routes available to tackle it.

* If we feel that the agent should not record these schema cache queries as counting towards the monitored app's query count, we can update the agent to stop doing so.
* If we wish to continue to count schema queries as monitored app queries, we'll have to refactor the assertion helper to support something like ">= 5" instead of simply "5" for the query count assertion, or do an even bigger testing overhaul to explicitly exclude queries that schema cache related.

I'll look at both approaches to give us some options.

**Comment by fallwith** [comment]
PR #1013 will eliminate the flickering/flapping test results related to the tallying of 5-8 SELECT statements instead of exactly 5 by relaxing the "exactly" assertion to be "greater than or equal to 5".

Issue #1014 will track the discussion of whether or not we should prevent the tallying of these schema/type cache queries in the first place.
