### ISSUE TITLE
Run EAP test plan through common Rails/Ruby versions

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/newrelic-ruby-agent#990]
The most common application setups for Ruby Agent customers are Rails 6.1/Ruby 2.7 and Rails 5.0/Ruby 2.5. 

Run the [EAP Performance Test Plan (Internal)](https://docs.google.com/document/d/15jXHjtxMRwHxYEknYho-Kl9LtChmVmD-tYiFoxJpRHg/edit?usp=sharing) through two applications with the same basic CRUD setup using these Rails/Ruby combinations. The EAP time period should be shortened: 1 week becomes 1 hour; 3 days become 30 minutes.

In addition, add some of the actions from [logging/log-jam (Internal)](https://source.datanerd.us/logging/log-jam) to generate logs so that we can compare the results with the early Sinatra test app.

The goal is to estimate whether different behavior can be expected when running the changes for the Logging Initiative through a Rails application.

If the Infrastructure agent is installed, use that for metrics. Otherwise, consider APM recordings of these values. Could also look at other tools such as JMeter, StackProf, RubyProf, RailsProf to avoid deployments.

Consider adding traffic test script using a tool like [foot_traffic](https://github.com/lewagon/foot_traffic).

**Comment by fallwith** [comment]
The Ruby agent playground has been updated with two new projects, `logging_rails61_stackprof` and `logging_rails_rubyprof`. Both use an identical Ruby 2.7 / Rails 6.1 test application. The `stackprof` version has stackprof middleware configured, and the `rubyprof` version uses a `ruby-prof` wrapper around the `rails` binary's content.

The projects contain the following files:

- **README.md:** This markdown file contains usage instructions for running the tests and storing the results.
- **tester:** This bash script front ends `curl` and `jq` to loop over input values used to perform Rails create, read, and delete operations.
- **timedtester:** This bash script will run `tester` in a loop for the given number of seconds.
- **dockerbuild:** This bash script will build a Docker image for testing.
- **dockerrun:** This bash script will conveniently front-end `docker run`.
- **cleanup:** This bash script performed after a run will move the project's `tmp` and `log` directories to the correct phase numbered subdirectory in a `results` directory, and then recreate the `tmp` and `log` directory structures with `.keep` files.

The `stackprof` project will produce output files at `tmp/stackprof-*.dump`

The `rubyprof` project will produce output files at `tmp/prof-*.(txt|html)`

The results of our recent runs using both projects have been recording at `ruby-agent/logging-eap-results`

Here are some pros and cons observed for the tests we did:

**Pros**
* With 100% self sufficiency, we managed to produce something that could give us a good initial result to indicate whether or not there were any obvious performance concerns.
* We managed to exercise common CRUD patterns for a popular Ruby/Rails combination and observe the related logging activity produced by it.
* The use of Docker should provide more consistent results between runs than using our own workstations

**Cons**
* Given that the test runs delete all database data that they create, we didn't bother to reset the database between runs. It's possible that not doing so introduced unwanted disparity in the results (a more recently run test will be operating with larger ActiveRecord id number values than tests ran earlier, for example).
* We did not produce significant load during testing
* We did not set things up to exercise a variety of different log levels
* The ruby-prof results seemed to have an unfortunate +/- 5% performance swing between runs that interfered with making comparisons
* The stackprof results were based on runs that came with unusually high miss rates of 26% and 46% percent.

After a group analysis and discussion, we've decided to continue to leverage our OATS platform for further testing and hope to shore up the gaps caused by our cons list in doing so.
